# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
np.show_config()

1.23.1
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['C:/ProgramData/Miniconda3/envs/pythonProject1\\Library\\lib']
    include_dirs = ['C:/ProgramData/Miniconda3/envs/pythonProject1\\Library\\include']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['C:/ProgramData/Miniconda3/envs/pythonProject1\\Library\\lib']
    include_dirs = ['C:/ProgramData/Miniconda3/envs/pythonProject1\\Library\\include']
    language = f77
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['C:/ProgramData/Miniconda3/envs/pythonProject1\\Library\\lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['C:/ProgramData/Miniconda3/envs/pyth

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
NullArr = np.zeros(10)
print(NullArr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
print("%d bytes" % (NullArr.size * NullArr.itemsize))

80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
NullArr = np.zeros(10)
NullArr[4] = 1
print(NullArr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
Vector = np.arange(10,50)
print(Vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [12]:
np.flip(Vector)
print(Vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
Matrix = np.arange(9).reshape(3,3)
Matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [14]:
nonZeroArray = np.nonzero([1,2,0,0,4,0])
nonZeroArray

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [15]:
Matrix = np.identity(3)
Matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [18]:
Matrix = np.random.random((3,3,3))
Matrix

array([[[0.67196691, 0.3489879 , 0.67636178],
        [0.59986463, 0.43984537, 0.30417796],
        [0.21881507, 0.48721871, 0.38737558]],

       [[0.1543246 , 0.18902304, 0.74024434],
        [0.7143608 , 0.10722217, 0.4419432 ],
        [0.72462996, 0.71487912, 0.87152725]],

       [[0.25193251, 0.96470216, 0.73879019],
        [0.93083823, 0.33290762, 0.11218601],
        [0.79211524, 0.89123618, 0.45808264]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [19]:
Matrix = np.random.random((10,10))
min = Matrix.min()
max = Matrix.max()
print(min, max)

0.019908964909479354 0.9968044715551194


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [21]:
vec = np.random.random(30)
vec.mean()

0.5884592407432961

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [22]:
arr = np.ones((10,10))
arr[1:-1,1:-1] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [24]:
arr = np.ones((3,3))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
arr

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [26]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [27]:
arr = np.diag(1+np.arange(4),k=-1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [28]:
arr = np.zeros((8,8),dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [29]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [30]:
arr = np.array([[0,1], [1,0]])
arr2 = np.tile(arr,(4,4))
arr2

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [33]:
arr = np.random.random((5,5))
arr = (arr-arr.min())/(arr.max()-arr.min())
arr

array([[0.00862413, 0.29504792, 0.53569273, 0.40524217, 0.07916237],
       [0.69922724, 0.87654172, 0.51322244, 0.33107346, 0.723653  ],
       [0.87754925, 0.92329222, 0.86811273, 0.86532001, 0.03059987],
       [0.8965415 , 0.86896977, 0.49367748, 0.3601451 , 1.        ],
       [0.17557446, 0.8103024 , 0.        , 0.62856154, 0.357743  ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [34]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

C:\Users\Anna\AppData\Local\Temp\ipykernel_9960\2911720781.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [35]:
arr = np.dot(np.ones((5,3)), np.ones((3,2)))
arr

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [38]:
arr = np.arange(11)
arr[(3 < arr) & (arr <= 8)] *= -1
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [46]:
2 << arr >> 2
arr <- arr
1j*arr
arr/1/1

array([ 0.,  1.,  2.,  3., -4., -5., -6., -7., -8.,  9., 10.])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [47]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Anna\AppData\Local\Temp\ipykernel_9960\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Anna\AppData\Local\Temp\ipykernel_9960\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [48]:
arr = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(arr)), arr))

[  4.  -2.  -5.  -8.  -4.  -8. -10.  -8.  -4.  10.]


#### 30. How to find common values between two arrays? (★☆☆)

In [49]:
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)
print(np.intersect1d(arr1,arr2))

[1 4 6 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
defaults = np.seterr(all="ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [50]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Anna\AppData\Local\Temp\ipykernel_9960\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [52]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print(yesterday)
today     = np.datetime64('today', 'D')
print(today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(tomorrow)

2022-10-30
2022-10-31
2022-11-01


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [53]:
July = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
July

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [54]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [56]:
arr = np.random.uniform(0,10,10)
print (arr.astype(int))
print (np.trunc(arr))
print (np.floor(arr))
print (np.ceil(arr)-1)
print (arr - arr%1)

[7 9 9 5 9 5 1 5 9 4]
[7. 9. 9. 5. 9. 5. 1. 5. 9. 4.]
[7. 9. 9. 5. 9. 5. 1. 5. 9. 4.]
[7. 9. 9. 5. 9. 5. 1. 5. 9. 4.]
[7. 9. 9. 5. 9. 5. 1. 5. 9. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [57]:
arr = np.zeros((5,5))
arr += np.arange(5)
arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [59]:
def generate():
    for x in range(10):
        yield x
arr = np.fromiter(generate(),dtype=float,count=-1)
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [60]:
arr = np.linspace(0,1,11,endpoint=False)[1:]
arr

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [63]:
arr = np.random.random(10)
print(arr)
arr.sort()
print(arr)

[0.87729668 0.16550615 0.25713923 0.84678704 0.14449975 0.80576929
 0.73939735 0.33475223 0.61691885 0.47260553]
[0.14449975 0.16550615 0.25713923 0.33475223 0.47260553 0.61691885
 0.73939735 0.80576929 0.84678704 0.87729668]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [64]:
arr = np.arange(10)
np.add.reduce(arr)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [66]:
A = np.random.randint(0,2,10)
B = np.random.randint(0,2,10)
result = np.array_equal(A, B)
result

False

#### 43. Make an array immutable (read-only) (★★☆)

In [68]:
ReadArr = np.zeros(6)
ReadArr.flags.writeable = False
ReadArr[3]=10

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [70]:
arr = np.random.random((10,2))
X,Y = arr[:,0], arr[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.79431992 0.45215908 0.52997598 1.19967342 1.12960808 0.88001932
 0.58118979 0.19119655 0.96389548 0.95798134]
[0.14063695 0.95296126 0.69085603 0.89533623 0.60753936 0.27065205
 0.14398138 0.73071029 0.17178805 1.07795493]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [72]:
arr = np.random.random(10)
print(arr)
arr[arr.argmax()] = 0
arr

[0.17247299 0.29802052 0.27036586 0.10344837 0.24743143 0.30693099
 0.69215821 0.568915   0.18020446 0.35695644]


array([0.17247299, 0.29802052, 0.27036586, 0.10344837, 0.24743143,
       0.30693099, 0.        , 0.568915  , 0.18020446, 0.35695644])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [3]:
arr = np.zeros((5,5), [('x',float),('y',float)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
arr

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [4]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
result = np.linalg.det(C)
print(result)

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [6]:
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).eps)
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
   
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).max)
    print(np.iinfo(dtype).min)

1.1920929e-07
-3.4028235e+38
3.4028235e+38
2.220446049250313e-16
-1.7976931348623157e+308
1.7976931348623157e+308
127
-128
2147483647
-2147483648
9223372036854775807
-9223372036854775808


#### 49. How to print all the values of an array? (★★☆)

In [9]:
arr = np.zeros((5, 5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [11]:
array = np.arange(100)
value = np.random.uniform(0,100)
index = (np.abs(array-value)).argmin()
print(array[index])

31


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [12]:
array = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(array)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\Anna\AppData\Local\Temp\ipykernel_9752\3840284578.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  array = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [13]:
W = np.random.random((100,2))
X,Y = np.atleast_2d(W[:,0], W[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         1.00371596 1.02085757 ... 0.42463238 0.2478735  0.82738842]
 [1.00371596 0.         0.02236619 ... 0.68264872 0.77247944 0.48325833]
 [1.02085757 0.02236619 0.         ... 0.69420067 0.78812875 0.50493139]
 ...
 [0.42463238 0.68264872 0.69420067 ... 0.         0.1930696  0.72202774]
 [0.2478735  0.77247944 0.78812875 ... 0.1930696  0.         0.68276652]
 [0.82738842 0.48325833 0.50493139 ... 0.72202774 0.68276652 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [15]:
a = np.arange(10, dtype=np.float32)
print(a)
a = a.astype(np.int32, copy=False)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [16]:
from io import StringIO
string = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
res = np.genfromtxt(string, delimiter=",", dtype=np.int)
print(res)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\Anna\AppData\Local\Temp\ipykernel_9752\4214514903.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  res = np.genfromtxt(string, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [17]:
arr = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(arr):
    print(index, value)
for index in np.ndindex(arr.shape):
    print(index, arr[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [18]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [19]:
n = 10
p = 3
arr = np.zeros((n,n))
np.put(arr, np.random.choice(range(n*n), p, replace=False),1)
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [21]:
arr = np.random.rand(5, 10)
print(arr)
res = arr - arr.mean(axis=1, keepdims=True)
print("------------------------")
print(res)

[[0.37248829 0.52046819 0.08352541 0.3438295  0.02453838 0.39759657
  0.04448098 0.33055679 0.51873925 0.13161185]
 [0.01109396 0.11476834 0.75315196 0.31345191 0.19171728 0.61792581
  0.43614469 0.55255115 0.73312469 0.67814401]
 [0.50827119 0.45344532 0.44643715 0.77342467 0.39444685 0.53258509
  0.55621334 0.15300963 0.09453119 0.94294579]
 [0.73603531 0.55348504 0.07449154 0.23322281 0.31806868 0.19806609
  0.54774704 0.30457861 0.26418431 0.45909079]
 [0.90514515 0.43292893 0.71336572 0.80056092 0.05528687 0.62964166
  0.09057746 0.42935006 0.06405103 0.61452476]]
------------------------
[[ 0.09570477  0.24368467 -0.19325812  0.06704598 -0.25224514  0.12081305
  -0.23230254  0.05377327  0.24195573 -0.14517167]
 [-0.42911342 -0.32543904  0.31294458 -0.12675547 -0.2484901   0.17771843
  -0.00406269  0.11234377  0.29291731  0.23793663]
 [ 0.02274017 -0.03208571 -0.03909388  0.28789365 -0.09108417  0.04705407
   0.07068232 -0.33252139 -0.39099983  0.45741477]
 [ 0.36713829  0.1845880

#### 59. How to sort an array by the nth column? (★★☆)

In [23]:
arr = np.random.randint(0,10,(3,3))
print(arr)
print(arr[arr[:,1].argsort()])

[[9 7 2]
 [2 9 0]
 [6 3 4]]
[[6 3 4]
 [9 7 2]
 [2 9 0]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [24]:
arr = np.random.randint(0,3,(3,3))
~arr.any(axis=0).any()

False

#### 61. Find the nearest value from a given value in an array (★★☆)

In [26]:
arr = np.random.uniform(0,1,20)
a = 0.5
m = arr.flat[np.abs(arr - a).argmin()]
print(m)

0.5037074465169795


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [27]:
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)

iterator = np.nditer([a,b,None])
for x,y,z in iterator: z[...] = x + y
print(iterator.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [28]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

x = NamedArray(np.arange(5), "range_5")
print (x.name)

range_5


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [32]:
vec = np.ones(5)
print(vec)
I = np.random.randint(0,len(vec),20)
print(I)
np.add.at(vec, I, 1)
print(vec)

[1. 1. 1. 1. 1.]
[3 2 3 3 0 4 4 0 0 4 0 2 4 4 4 1 1 2 2 1]
[5. 4. 5. 4. 7.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [33]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
F

array([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [34]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
n

8

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [36]:
A = np.random.randint(0,10,(3,3,3,3))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[42 55 25]
 [30 24 42]
 [44 57 37]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [38]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
sums = np.bincount(S, weights=D)
counts = np.bincount(S)
means = sums / counts
means

array([0.45184937, 0.65437503, 0.43053302, 0.45499985, 0.32104566,
       0.48974487, 0.18699615, 0.4303311 , 0.53349345, 0.49794427])

#### 69. How to get the diagonal of a dot product? (★★★)

In [39]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

result = np.diag(np.dot(A, B))
result

array([1.18680189, 0.73046519, 2.61449634, 1.61807406, 1.56467955])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [40]:
vec = np.array([1,2,3,4,5])
num = 3
newVec = np.zeros(len(vec) + (len(vec)-1)*(num))
newVec[::num+1] = vec
print(newVec)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [41]:
array1 = np.ones((5,5,3))
array2 = 2*np.ones((5,5))
print(array1 * array2[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [42]:
Arr = np.arange(25).reshape(5,5)
print(Arr)
Arr[[0,1]] = Arr[[1,0]]
print(Arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [43]:
f = np.random.randint(0,100,(10,3))
F = np.roll(f.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 58) ( 0, 59) ( 4, 16) ( 4, 41) ( 5, 14) ( 5, 17) ( 7, 35) ( 7, 49)
 ( 8,  9) ( 8, 62) ( 9, 62) (14, 17) (16, 41) (28, 63) (28, 87) (31, 76)
 (31, 96) (33, 59) (33, 63) (35, 49) (49, 73) (49, 78) (49, 91) (49, 99)
 (58, 59) (59, 63) (63, 87) (73, 78) (76, 96) (91, 99)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [44]:
C = np.bincount([1,1,2,3,4,4,6])

A = np.repeat(np.arange(len(C)), C)
A

array([1, 1, 2, 3, 4, 4, 6])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [45]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
arr = np.arange(20)
print(moving_average(arr, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [48]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [49]:
arr = np.random.randint(0,2,100)
np.logical_not(arr, out=arr)
arr = np.random.uniform(-1.0,1.0,100)
np.negative(arr, out=arr)

array([-2.38881579e-01,  5.03267530e-01, -1.00526749e-01,  3.57321466e-01,
        9.44914596e-01, -5.36864168e-01,  3.37835775e-01,  8.97926871e-01,
       -6.28243538e-01,  4.64459814e-01, -7.72877822e-02, -1.53928947e-01,
        2.05384580e-01, -5.43410822e-02,  7.11180567e-01,  7.73901831e-01,
        3.44172142e-01, -3.46994854e-01, -6.82603527e-01,  6.63330428e-02,
        1.82060952e-01,  1.93092774e-01,  2.97569806e-01, -4.05326859e-01,
       -3.09705915e-01,  8.26912784e-01,  6.92486712e-01, -5.68537172e-01,
       -8.32861986e-01,  3.32520066e-01, -4.96477897e-01, -2.76688202e-01,
        2.66232268e-01,  4.33845367e-01, -1.09964046e-01,  8.69968097e-01,
       -1.36267113e-01,  5.11821196e-01, -9.74754934e-02, -4.93415228e-01,
       -3.00978166e-01, -5.02167191e-01, -9.83835555e-01, -2.42622122e-01,
        4.55763739e-01,  6.62207832e-02,  5.45676832e-01,  4.86918178e-01,
       -4.07183907e-01, -4.95946420e-01,  2.45185470e-01,  6.14270498e-01,
       -5.85586368e-01,  

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [50]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[5.33260939 5.28867082 3.29292151 1.11372122 1.08460743 4.08846635
 2.83032226 7.31224659 3.62541437 2.60983758]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [51]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[4.26796582e+00 9.70425087e+00 4.98262445e+00 4.39148286e+00
  5.75809417e+00 7.20256572e+00 1.11771355e+01 5.39233502e+00
  3.23600026e+00 1.85776565e+00]
 [6.66839154e+00 1.26869380e+00 7.22178878e+00 4.12639537e+00
  9.30720911e+00 3.18582505e+00 1.40835252e+01 5.48788286e+00
  5.57861790e+00 9.54548908e+00]
 [1.71139632e+00 7.09514547e+00 1.75730335e-01 4.06742197e+00
  1.74132490e+00 1.05179815e+00 6.76344266e+00 5.54433814e-01
  1.51115708e+00 1.41948423e+00]
 [1.33831299e+01 1.88276476e+01 4.18401975e-01 8.21729866e+00
  3.46987615e-01 1.29122531e+01 6.17686946e+00 2.29145023e+00
  1.39645289e+00 1.10525495e+01]
 [1.79403266e+00 3.62165529e+00 6.18539059e+00 3.76548770e-01
  7.69044884e+00 1.40233648e+00 1.27514520e+01 5.40229791e+00
  4.49636645e+00 4.46743826e+00]
 [4.68302863e+00 1.01701138e+01 1.08858773e+01 1.19807306e+01
  1.10680053e+01 1.41417826e+01 1.67885605e+01 1.20945491e+01
  9.09538596e+00 2.97756170e+00]
 [1.14923012e+00 6.61729785e+00 1.07374096e+01 8.17034362e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [54]:
arr = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
s = np.array(list(Z.shape)).astype(int)
R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
arr_start = (P-Rs//2)
arr_stop  = (P+Rs//2)+Rs%2
R_start = (R_start - np.minimum(arr_start,0)).tolist()
arr_start = (np.maximum(arr_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(arr_stop-s,0))).tolist()
arr_stop = (np.minimum(arr_stop,s)).tolist()
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
a = [slice(start,stop) for start,stop in zip(arr_start,arr_stop)]
R[r] = arr[a]
print(arr)
print(R)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [55]:
arr = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(arr,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [57]:
arr = np.random.uniform(0,1,(4,4))
print(arr)

U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)

print(rank)

[[0.2879511  0.3130242  0.57196186 0.82902336]
 [0.95644781 0.18175646 0.90344253 0.41283138]
 [0.87686299 0.5020349  0.5319578  0.53851391]
 [0.36306322 0.05843359 0.74936222 0.18552041]]
2


#### 83. How to find the most frequent value in an array?

In [58]:
arr = np.random.randint(0,10,50)
print(np.bincount(arr).argmax())

3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [61]:
arr = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (arr.shape[0]-3)
j = 1 + (arr.shape[1]-3)
C = stride_tricks.as_strided(arr, shape=(i, j, n, n), strides=arr.strides + arr.strides)
print(C)

[[[[3 1 4]
   [1 1 3]
   [2 4 3]]

  [[1 4 1]
   [1 3 4]
   [4 3 4]]

  [[4 1 1]
   [3 4 2]
   [3 4 1]]

  [[1 1 3]
   [4 2 2]
   [4 1 1]]

  [[1 3 4]
   [2 2 4]
   [1 1 2]]

  [[3 4 2]
   [2 4 3]
   [1 2 1]]

  [[4 2 0]
   [4 3 3]
   [2 1 3]]

  [[2 0 0]
   [3 3 3]
   [1 3 2]]]


 [[[1 1 3]
   [2 4 3]
   [0 1 3]]

  [[1 3 4]
   [4 3 4]
   [1 3 1]]

  [[3 4 2]
   [3 4 1]
   [3 1 3]]

  [[4 2 2]
   [4 1 1]
   [1 3 2]]

  [[2 2 4]
   [1 1 2]
   [3 2 1]]

  [[2 4 3]
   [1 2 1]
   [2 1 4]]

  [[4 3 3]
   [2 1 3]
   [1 4 1]]

  [[3 3 3]
   [1 3 2]
   [4 1 1]]]


 [[[2 4 3]
   [0 1 3]
   [0 0 4]]

  [[4 3 4]
   [1 3 1]
   [0 4 4]]

  [[3 4 1]
   [3 1 3]
   [4 4 0]]

  [[4 1 1]
   [1 3 2]
   [4 0 3]]

  [[1 1 2]
   [3 2 1]
   [0 3 2]]

  [[1 2 1]
   [2 1 4]
   [3 2 1]]

  [[2 1 3]
   [1 4 1]
   [2 1 1]]

  [[1 3 2]
   [4 1 1]
   [1 1 4]]]


 [[[0 1 3]
   [0 0 4]
   [1 1 4]]

  [[1 3 1]
   [0 4 4]
   [1 4 1]]

  [[3 1 3]
   [4 4 0]
   [4 1 1]]

  [[1 3 2]
   [4 0 3]
   [1 1 4]]

  [[3 2 1]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [62]:
class Sym(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Sym, self).__setitem__((i,j), value)
        super(Sym, self).__setitem__((j,i), value)

def symetric(x):
    return np.asarray(x + x.T - np.diag(x.diagonal())).view(Sym)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 8 15  9 12 16]
 [15  3  7 10 12]
 [ 9  7  9 42 11]
 [12 10 42  0 11]
 [16 12 11 11  4]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [63]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [64]:
arr = np.ones((16,16))
num = 4
Summ = np.add.reduceat(np.add.reduceat(arr, np.arange(0, arr.shape[0], num), axis=0),
                                       np.arange(0, arr.shape[1], num), axis=1)
print(Summ)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [65]:
def iterate(G):
    N = (G[0:-2,0:-2] + G[0:-2,1:-1] + G[0:-2,2:] +
         G[1:-1,0:-2]                + G[1:-1,2:] +
         G[2:  ,0:-2] + G[2:  ,1:-1] + G[2:  ,2:])
    
    birth = (N==3) & (G[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (G[1:-1,1:-1]==1)
    G[...] = 0
    G[1:-1,1:-1][birth | survive] = 1
    return G

G = np.random.randint(0,2,(50,50))
for i in range(100): G = iterate(G)
G

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

#### 89. How to get the n largest values of an array (★★★)

In [66]:
arr = np.arange(5000)
np.random.shuffle(arr)
n = 3
print (arr[np.argsort(arr)[-n:]])

[4997 4998 4999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [67]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [69]:
arr = np.array([("test", 2.5, 3),
              ("laba 2", 3.6, 2)])
R = np.core.records.fromarrays(arr.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'test', 2.5, 3) (b'laba 2', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [74]:
arr = np.random.rand(100)

%timeit np.power(arr,3)
%timeit arr*arr*arr
%timeit np.einsum('i,i,i->i',arr,arr,arr)

8.76 µs ± 659 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
1.99 µs ± 104 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
6.22 µs ± 361 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [75]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 2 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [76]:
arr = np.random.randint(0,5,(10,3))
print(arr)
E = np.all(arr[:,1:] == arr[:,:-1], axis=1)
U = arr[~E]
print(U)

[[0 4 2]
 [4 4 2]
 [4 3 4]
 [1 4 3]
 [4 4 0]
 [3 1 1]
 [0 1 1]
 [3 2 3]
 [0 0 3]
 [0 2 3]]
[[0 4 2]
 [4 4 2]
 [4 3 4]
 [1 4 3]
 [4 4 0]
 [3 1 1]
 [0 1 1]
 [3 2 3]
 [0 0 3]
 [0 2 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [78]:
arr = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(arr[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [79]:
arr = np.random.randint(0,2,(6,3))
u = np.unique(arr, axis=0)
print(u)

[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [80]:
A = np.random.uniform(0,1,3)
B = np.random.uniform(0,1,3)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B) 
np.einsum('i,j->ij', A, B)

array([[7.97269508e-01, 9.62993078e-04, 1.85784034e-01],
       [5.25340588e-01, 6.34539945e-04, 1.22417693e-01],
       [5.15022050e-01, 6.22076555e-04, 1.20013212e-01]])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [82]:
ph = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*ph*np.cos(ph)
y = a*ph*np.sin(ph)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)     
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [83]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [84]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.23352363  0.21543022]
