In [1]:
import numpy as np
print(np.__version__)
np.show_config()

1.23.4
openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBO

In [9]:
#3-4
vector0=np.zeros(10)
print(vector0)
print("%d bytes" % (vector0.size * vector0.itemsize))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
80 bytes


In [10]:
#5
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [11]:
#6
vector0 = np.zeros(10)
vector0[4] = 1
print(vector0)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [12]:
#7
vector0 = np.arange(10,50)
print(vector0)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
#8
np.flip(vector0)
print(vector0)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [16]:
#9
matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
#10
non_zero_array = np.nonzero([1,2,0,0,4,0])
print(non_zero_array)

(array([0, 1, 4], dtype=int64),)


In [19]:
#11
matrix = np.identity(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
#12
matrix = np.random.random((3,3,3))
print(matrix)

[[[0.31211832 0.09988259 0.17808562]
  [0.87343601 0.68739669 0.27345812]
  [0.55889111 0.47972516 0.75976584]]

 [[0.85652068 0.7160108  0.6111867 ]
  [0.69423422 0.82831623 0.78846367]
  [0.43385045 0.90918304 0.31142587]]

 [[0.14928012 0.69562173 0.08543542]
  [0.67823982 0.97768609 0.9896729 ]
  [0.8683347  0.16269223 0.22892216]]]


In [28]:
#13
matrix = np.random.random((10,10))
min = matrix.min()
max = matrix.max()
print("min: ",min, "\nmax: ",max)

min:  0.002929038018836261 
max:  0.9994101909269258


In [30]:
#14
vector_random = np.random.random(30)
print(vector_random.mean())

0.5083564137413642


In [36]:
#15-16
array = np.ones((10,10))
array[1:-1,1:-1] = 0
print(array)
print("\n**************************************\n")
array = np.ones((3,3))
array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

**************************************

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [37]:
#17
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [40]:
#18
matrix = np.diag(1+np.arange(4),k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [41]:
#19
matrix = np.zeros((8,8),dtype=int)
matrix[1::2,::2] = 1
matrix[::2,1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [42]:
#20
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [44]:
#21
matrix = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [46]:
#22
matrix = np.random.random((5,5))
matrix = (matrix - np.mean (matrix)) / (np.std (matrix))
print(matrix)

[[-0.97828086 -1.30159855  0.57498166  1.07741887  1.35994327]
 [-1.03755921 -0.36398821 -0.58809658  1.17957822 -0.80460707]
 [ 0.8186603  -1.58207735  0.47207563 -1.1904659   0.79568865]
 [ 1.32954102  1.11695719 -0.16122438  0.8802217  -1.48880841]
 [ 0.93165749  0.09313978 -0.3769356  -1.52497906  0.76875742]]


In [47]:
#23
colorrgba = np.dtype({'names': ['r', 'g', 'b', 'a'], 'formats': [np.uint8, np.uint8, np.uint8, np.uint8]})
color = np.array([(220, 140, 20, 75)], dtype = colorrgba)
print(color)

[(220, 140, 20, 75)]


In [48]:
#24
matrix = np.dot(np.ones((5,3)), np.ones((3,2)))
print(matrix)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [49]:
#25
array = np.arange(11)
array[(3 < array) & (array <= 8)] *= -1
print(array)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [1]:
#26
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [7]:
#27
Z = np.arange(11)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)


[         1          1          4         27        256       3125
      46656     823543   16777216  387420489 1410065408]
[  0   1   2   4   8  16  32  64 128 256 512]
[False False False False False False False False False False False]
[0. +0.j 0. +1.j 0. +2.j 0. +3.j 0. +4.j 0. +5.j 0. +6.j 0. +7.j 0. +8.j
 0. +9.j 0.+10.j]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [11]:
#28
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\София\AppData\Local\Temp\ipykernel_16772\195352166.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\София\AppData\Local\Temp\ipykernel_16772\195352166.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [12]:
#29
array = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(array)), array))

[-3. -6.  8. -5. -4. -2.  3.  8. -9.  9.]


In [13]:
#30
array1 = np.random.randint(0,10,10)
array2 = np.random.randint(0,10,10)
print(np.intersect1d(array1,array2))

[0 1 4 5 9]


In [14]:
#31
defaults = np.seterr(all="ignore")

In [15]:
#32
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [16]:
#33
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2022-11-10 2022-11-11 2022-11-12


In [18]:
#34
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [19]:
#35
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [20]:
#36
array = np.random.uniform(0,10,10)
print (np.trunc(array))
print (array - array%1)
print (np.ceil(array)-1)
print (np.floor(array))

[1. 0. 4. 0. 3. 5. 5. 1. 7. 4.]
[1. 0. 4. 0. 3. 5. 5. 1. 7. 4.]
[1. 0. 4. 0. 3. 5. 5. 1. 7. 4.]
[1. 0. 4. 0. 3. 5. 5. 1. 7. 4.]


In [21]:
#37
matrix = np.zeros((5,5))
matrix += np.arange(5)
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [22]:
#38
def generate():
    for x in range(10):
        yield x
array = np.fromiter(generate(),dtype=float,count=-1)
print(array)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [23]:
#39
vector = np.linspace(0,1,11,endpoint=False)[1:]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [25]:
#40
vector = np.random.random(10)
print(vector)
vector.sort()
print(vector)

[0.82692295 0.97463421 0.38727314 0.70296544 0.6010555  0.66838287
 0.2486323  0.90672094 0.23753318 0.77719116]
[0.23753318 0.2486323  0.38727314 0.6010555  0.66838287 0.70296544
 0.77719116 0.82692295 0.90672094 0.97463421]


In [26]:
#41
print(np.add.reduce(np.arange(10)))

45


In [33]:
#42
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

False
False


In [38]:
#43
array = np.zeros(10)
array.flags.writeable = False

In [40]:
#44
array = np.random.random((10,2))
X,Y = array[:,0], array[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.9138121  0.67544496 0.93503694 0.82759936 0.86094934 0.25233022
 0.71052322 1.16911819 0.89789979 0.84189716]
[0.12239327 1.48061142 0.98486786 0.37958599 1.05354487 0.33662077
 0.2025623  0.77982536 0.81868969 1.49972872]


In [41]:
#45
vector = np.random.random(10)
vector[vector.argmax()] = 0
print(vector)

[0.06289902 0.54252615 0.86320188 0.91213477 0.29374082 0.
 0.76018063 0.55256221 0.28913372 0.53076141]


In [43]:
#46
array = np.zeros((5,5), [('x',float),('y',float)])
array['x'], array['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(array)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [44]:
#47
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [45]:
#48
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [46]:
#49
print(array)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [48]:
#50
array = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(array-v)).argmin()
print(array[index])

63


In [49]:
#51

array = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(array)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\София\AppData\Local\Temp\ipykernel_16772\549271312.py:3: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  array = np.zeros(10, [ ('position', [ ('x', float, 1),


In [50]:
#52
vector = np.random.random((100,2))
X,Y = np.atleast_2d(vector[:,0], vector[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.60151299 0.89295745 ... 0.62722722 0.33831037 0.86861422]
 [0.60151299 0.         0.59578006 ... 0.77110733 0.81029022 0.60828698]
 [0.89295745 0.59578006 0.         ... 0.53540014 0.86781133 0.05074949]
 ...
 [0.62722722 0.77110733 0.53540014 ... 0.         0.41967776 0.48685504]
 [0.33831037 0.81029022 0.86781133 ... 0.41967776 0.         0.82829666]
 [0.86861422 0.60828698 0.05074949 ... 0.48685504 0.82829666 0.        ]]


In [51]:
#53
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [52]:
#54
from io import StringIO
string = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
print(np.genfromtxt(string, delimiter=",", dtype=np.int))

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\София\AppData\Local\Temp\ipykernel_16772\3387853947.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(np.genfromtxt(string, delimiter=",", dtype=np.int))


In [53]:
#55
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [54]:
#56
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
print(np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) ))

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [56]:
#57
n = 10
p = 3
array = np.zeros((n,n))
np.put(array, np.random.choice(range(n*n), p, replace=False),1)
print(array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


In [57]:
#58
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[-0.28266477  0.14593092  0.50004431 -0.22370464  0.18165975 -0.15639237
   0.48416572  0.10905868 -0.39836123 -0.35973637]
 [ 0.15569221  0.33452483 -0.20984603 -0.16574269  0.22795168  0.14228391
  -0.28986337 -0.27827626 -0.1154376   0.19871331]
 [ 0.10820237 -0.36689279 -0.26628603  0.52666745 -0.09551869  0.10658873
  -0.21528954  0.18006102 -0.11829322  0.14076071]
 [-0.07700748 -0.3128527  -0.21256402  0.08575852 -0.04546977 -0.17237922
   0.54219798  0.1756857  -0.22804236  0.24467337]
 [ 0.48407954  0.35812297  0.45824288 -0.20491058  0.02137648 -0.14946903
  -0.33677179  0.02575587 -0.35514911 -0.30127723]]


In [59]:
#59
array = np.random.randint(0,10,(3,3))
print(array)
print("\n**************************************\n")
print(array[array[:,1].argsort()])

[[6 6 5]
 [2 7 7]
 [9 2 2]]

**************************************

[[9 2 2]
 [6 6 5]
 [2 7 7]]


In [60]:
#60
array = np.random.randint(0,3,(3,3))
~array.any(axis=0).any()

False

In [65]:
#61
array = np.random.uniform(0,1,20)
n = 0.5
print(array.flat[np.abs(array - n).argmin()])

0.4978621091727584


In [2]:
#62
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [3]:
#63
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

a = NamedArray(np.arange(5), "range_5")
print (a.name)

range_5


In [4]:
#64
vector = np.ones(5)
print(vector)
I = np.random.randint(0,len(vector),20)
print(I)
np.add.at(vector, I, 1)
print(vector)

[1. 1. 1. 1. 1.]
[1 1 3 0 3 2 3 1 4 2 1 1 1 3 3 3 3 1 4 2]
[2. 8. 4. 8. 3.]


In [5]:
#65
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [7]:
#66
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
print(len(np.unique(F)))


8


In [8]:
#67
a = np.random.randint(0,10,(3,4,3,4))
print(a.sum(axis=(-2,-1)))

[[42 49 60 36]
 [54 38 69 62]
 [42 53 45 66]]


In [10]:
#68
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
sums_of_d = np.bincount(S, weights=D)
counts_of_d = np.bincount(S)
means_of_d = sums_of_d / counts_of_d
print(means_of_d)


[0.54422703 0.53066998 0.66127929 0.55684213 0.80832404 0.45315399
 0.43758585 0.40748634 0.58618592 0.58085538]


In [11]:
#69
a = np.random.uniform(0,1,(5,5))
b = np.random.uniform(0,1,(5,5))
print(np.diag(np.dot(a, b)))

[0.42448214 1.12367973 0.50479385 1.36900908 1.29592559]


In [13]:
#70
vector = np.array([1,2,3,4,5])
num = 3
vector0 = np.zeros(len(vector) + (len(vector)-1)*(num))
vector0[::num+1] = vector
print(vector0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [14]:
#71
array1 = np.ones((5,5,3))
array2 = 2*np.ones((5,5))
print(array1 * array2[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [16]:
#72
array = np.arange(25).reshape(5,5)
print(array)
print("\n**************************************\n")
array[[0,1]] = array[[1,0]]
print(array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

**************************************

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [17]:
#73
faces = np.random.randint(0,100,(10,3))
f = np.roll(faces.repeat(2,axis=1),-1,axis=1)
f = f.reshape(len(f)*3,2)
f = np.sort(f,axis=1)
g = f.view( dtype=[('p0',f.dtype),('p1',f.dtype)] )
g = np.unique(g)
print(g)

[( 9, 46) ( 9, 50) (17, 19) (17, 61) (18, 20) (18, 25) (19, 61) (20, 25)
 (21, 44) (21, 76) (22, 31) (22, 39) (31, 39) (37, 56) (37, 58) (44, 76)
 (46, 50) (46, 60) (46, 79) (51, 56) (51, 89) (55, 57) (55, 59) (56, 58)
 (56, 89) (57, 59) (58, 68) (58, 85) (60, 79) (68, 85)]


In [18]:
#74
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [19]:
#75
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [20]:
#76
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [21]:
#77
array = np.random.randint(0,2,100)
np.logical_not(array, out=array)
array = np.random.uniform(-1.0,1.0,100)
np.negative(array, out=array)

array([-0.50945644,  0.25777247,  0.84734031, -0.6296838 ,  0.69052698,
       -0.76465195, -0.14115025,  0.01922973, -0.08351274, -0.32793803,
        0.82689922,  0.92577282,  0.93918621, -0.25005704, -0.68207571,
        0.7027213 ,  0.56354458, -0.53897386,  0.06557902,  0.09536027,
        0.28976377, -0.24221651, -0.63248813,  0.97071381,  0.62753163,
        0.79257215, -0.25044751,  0.14401646,  0.30683101, -0.06524626,
       -0.32264543,  0.66224313, -0.69410602,  0.89612104, -0.10376968,
       -0.11747748, -0.28739255, -0.49840186,  0.54255922,  0.27273205,
       -0.71136006,  0.14829546,  0.20048782,  0.63016793,  0.01748502,
       -0.63527334,  0.35495926, -0.7327529 , -0.63922818,  0.58357848,
       -0.60330058,  0.46444266,  0.48240119,  0.7129181 , -0.40710141,
       -0.65248569,  0.94104106,  0.50162674,  0.11625359, -0.40481249,
       -0.67103684, -0.93168407,  0.10942751,  0.11788758,  0.53183288,
        0.89050671, -0.7736688 ,  0.25707023, -0.39814491, -0.04

In [22]:
#78
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[5.24727455 5.136495   3.31004881 4.89804645 4.52954698 0.60948034
 2.89918407 2.88089513 9.16898132 4.99820648]


In [23]:
#79
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[10.27093442  3.06737318  3.22322536  4.59994343 12.7491369   9.25556704
   2.85282808  3.45299493  6.6791557   7.15885096]
 [14.25485888  2.67420103  3.25583652  4.88930769 16.39787134 12.73641312
   6.14467301  1.50533287  6.61689906 10.15256052]
 [ 1.88219164  0.19844495  7.72910849  0.98390444  2.62171845  5.04269419
   5.46095176 14.11912025 11.50553399  0.23690337]
 [13.97320702  3.86016577 10.02167435  2.04003181 17.61423584  7.08241919
   8.45164484  8.58655042 13.4351446  13.18949334]
 [14.27741427  4.0128432   1.87306435  6.3026604  16.11727653 13.86113581
   5.64436582  0.07551319  5.22425159  9.50571689]
 [ 5.99114796 13.16105942  5.66513326 12.35608172  4.05189836  2.04266083
  13.86957716  2.42109281  1.881078    9.26359696]
 [13.59274707  1.09143945  7.20165191  0.80781806 16.6521729   9.0007795
   7.08025373  5.88264826 10.60516118 11.55153568]
 [ 2.04018316  6.0026279  13.34833839  6.4023137   7.43113684  6.07986989
   0.12343782 17.93344801 17.06908792  5.86607359]
 

In [25]:
#81
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [27]:
#82
matrix = np.random.uniform(0,1,(4,4))
u, s, v = np.linalg.svd(matrix)
rank = np.sum(s > 1e-10)
print(rank)

4


In [28]:
#83
array = np.random.randint(0,10,50)
print(np.bincount(array).argmax())

2


In [30]:
#84
array = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (array.shape[0]-3)
j = 1 + (array.shape[1]-3)
c = stride_tricks.as_strided(array, shape=(i, j, n, n), strides=array.strides + array.strides)
print(c)

[[[[4 3 1]
   [2 1 4]
   [2 3 0]]

  [[3 1 0]
   [1 4 3]
   [3 0 4]]

  [[1 0 3]
   [4 3 2]
   [0 4 2]]

  [[0 3 2]
   [3 2 3]
   [4 2 2]]

  [[3 2 1]
   [2 3 3]
   [2 2 4]]

  [[2 1 2]
   [3 3 2]
   [2 4 2]]

  [[1 2 3]
   [3 2 4]
   [4 2 1]]

  [[2 3 3]
   [2 4 4]
   [2 1 0]]]


 [[[2 1 4]
   [2 3 0]
   [0 3 4]]

  [[1 4 3]
   [3 0 4]
   [3 4 0]]

  [[4 3 2]
   [0 4 2]
   [4 0 4]]

  [[3 2 3]
   [4 2 2]
   [0 4 4]]

  [[2 3 3]
   [2 2 4]
   [4 4 0]]

  [[3 3 2]
   [2 4 2]
   [4 0 1]]

  [[3 2 4]
   [4 2 1]
   [0 1 0]]

  [[2 4 4]
   [2 1 0]
   [1 0 0]]]


 [[[2 3 0]
   [0 3 4]
   [3 1 0]]

  [[3 0 4]
   [3 4 0]
   [1 0 1]]

  [[0 4 2]
   [4 0 4]
   [0 1 1]]

  [[4 2 2]
   [0 4 4]
   [1 1 4]]

  [[2 2 4]
   [4 4 0]
   [1 4 1]]

  [[2 4 2]
   [4 0 1]
   [4 1 4]]

  [[4 2 1]
   [0 1 0]
   [1 4 2]]

  [[2 1 0]
   [1 0 0]
   [4 2 2]]]


 [[[0 3 4]
   [3 1 0]
   [2 1 3]]

  [[3 4 0]
   [1 0 1]
   [1 3 0]]

  [[4 0 4]
   [0 1 1]
   [3 0 0]]

  [[0 4 4]
   [1 1 4]
   [0 0 2]]

  [[4 4 0]
   

In [31]:
#85
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 9 12 11  8  8]
 [12  9  8 10  2]
 [11  8  1 42  2]
 [ 8 10 42  3 15]
 [ 8  2  2 15  9]]


In [37]:
#86
p, n = 10, 20
m = np.ones((p,n,n))
v = np.ones((p,n,1))
s = np.tensordot(m, v, axes=[[0, 2], [0, 1]])
print(s)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [39]:
#87
array = np.ones((16,16))
num = 4
block_sum = np.add.reduceat(np.add.reduceat(array, np.arange(0, array.shape[0], num), axis=0),
                                       np.arange(0, array.shape[1], num), axis=1)
print(block_sum)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [40]:
#88
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [41]:
#89
array = np.arange(3000)
np.random.shuffle(array)
n = 4
print (array[np.argsort(array)[-n:]])

[2996 2997 2998 2999]


In [42]:
#90
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))


[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [43]:
#91
array = np.array([("hello", 6.7, 4),
              ("world", 2.2, 8)])
R = np.core.records.fromarrays(array.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'hello', 6.7, 4) (b'world', 2.2, 8)]


In [45]:
#92
Z = np.random.rand(100)

%timeit np.power(Z,3)
%timeit Z*Z*Z
%timeit np.einsum('i,i,i->i',Z,Z,Z)

4.23 µs ± 360 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
1e+03 ns ± 21.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
2.98 µs ± 191 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [46]:
#93
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 2 3 4 6]


In [47]:
#94
matrix = np.random.randint(0,5,(10,3))
print(matrix)
e = np.all(matrix[:,1:] == matrix[:,:-1], axis=1)
u = matrix[~e]
print(u)

[[1 2 3]
 [0 4 3]
 [4 0 4]
 [4 2 1]
 [2 4 1]
 [3 2 0]
 [1 1 4]
 [2 1 0]
 [4 0 0]
 [4 3 4]]
[[1 2 3]
 [0 4 3]
 [4 0 4]
 [4 2 1]
 [2 4 1]
 [3 2 0]
 [1 1 4]
 [2 1 0]
 [4 0 0]
 [4 3 4]]


In [48]:
#95
array = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(array[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [49]:
#96
array = np.random.randint(0,2,(6,3))
u = np.unique(array, axis=0)
print(u)

[[0 0 1]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 1]]


In [50]:
#97
A = np.random.uniform(0,1,3)
B = np.random.uniform(0,1,3)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B) 
np.einsum('i,j->ij', A, B)

array([[1.74045286e-02, 1.17607675e-01, 1.34348823e-03],
       [9.35255079e-02, 6.31980204e-01, 7.21940952e-03],
       [6.47891826e-04, 4.37800144e-03, 5.00119863e-05]])

In [51]:
#98
ph = np.arange(0, 10*np.pi, 0.1)
A = 1
X = A*ph*np.cos(ph)
Y = A*ph*np.sin(ph)

dr = (np.diff(X)**2 + np.diff(Y)**2)**.5 
R = np.zeros_like(X)
R[1:] = np.cumsum(dr)                
r_int = np.linspace(0, R.max(), 200)
x_int = np.interp(r_int, R, X)     
y_int = np.interp(r_int, R, Y)

In [52]:
#99
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [53]:
#100
X = np.random.randn(100) 
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.23956922  0.1411959 ]
