# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np 

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
print(np.show_config())

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
x = np.zeros(10)
print(x)

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
x = np.array([100, 20, 34]) 
print("Memory size of a NumPy array:", x.nbytes)

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
print(np.info(np.add))

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
x = np.zeros(10)
x[5] = 1
print(x)

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
v = np.arange(10,49)
print(v)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
print("Reverse vector: ")
v = v[::-1]
print(v)

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
x = np.arange(0, 8).reshape(3,3)
print(x)

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [2]:
x = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(x)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [3]:
array_2D=np.identity(3)
print(array_2D)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
x = np.random.random((3,3,3))
print(x)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [5]:
x = np.random.random((10,10))
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values: ", xmin, " ", xmax)

Minimum and Maximum Values:  0.0034408376600129076   0.9821292411861859


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [7]:
x = np.random.random(30)
x.mean()
print(x)

[0.55568973 0.39521152 0.12581364 0.39361555 0.47675642 0.34079768
 0.17654103 0.25703854 0.18246119 0.25221408 0.01787573 0.58492453
 0.92802097 0.42887552 0.6511412  0.55141987 0.55869964 0.34021399
 0.38969537 0.77963567 0.60837557 0.98556579 0.1516324  0.75565653
 0.37947381 0.7211221  0.95102442 0.84090301 0.15150341 0.68076394]


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [11]:
Z = np.ones((5,5))
Z[1:-1,1:-1]=0
print(Z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [14]:
x = np.ones((3, 3))
y = np.pad(array=x, pad_width=1, mode='constant')
print(y)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [21]:
0 * np.nan              #nan
np.nan == np.nan        #false
np.inf > np.nan         #false
np.nan - np.nan         #nan
np.nan in set([np.nan]) #true
0.3 == 3 * 0.1          #false

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [23]:
x = np.array([1, 2, 3, 4])
np.diag(1+np.arange(4), k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [24]:
x = np.zeros((8, 8))
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [25]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [26]:
x = np.array([[0,1], [1,0]])
ar = np.tile(x,(4,4))
print(ar)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [28]:
x = np.random.random((5,5))
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

After normalization:
[[0.49204551 0.80793384 0.28222893 0.33315739 0.70427424]
 [0.78031927 0.66021816 0.0111026  0.21021147 0.85331325]
 [0.39260603 0.05505351 0.56467474 0.72817393 0.06957114]
 [1.         0.19597607 0.71166161 0.49038249 0.97102431]
 [0.         0.41687085 0.70217054 0.94940073 0.38787872]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [31]:
color = np.dtype([("r", np.ubyte, (1,)),
                  ("g", np.ubyte, (1,)),
                  ("b", np.ubyte, (1,)),
                  ("a", np.ubyte, (1,))])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [35]:
x = np.random.random((5,3))
y = np.random.random((3,2))
z = np.dot(x, y)
print("Product of two arrays:")
print(z)

Product of two arrays:
[[1.68507893 1.43335885]
 [1.41470745 1.32322557]
 [1.26229244 1.31527897]
 [1.11449973 1.31440477]
 [0.86566011 1.08926899]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [54]:
arr = np.arange(1,10)
x = (arr > 3) & (arr < 8)
arr[x] *= -1
print(arr)

[ 1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [52]:
print(sum(range(5),-1)) #9
from numpy import *
print(sum(range(5),-1)) #10

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [65]:
Z = np.arange(1,5)
Z ** Z      #array([  1,   4,  27, 256])     
2 << Z >> 2 #array([1, 2, 4, 8], dtype=int32)
Z <- Z      #array([False, False, False, False])
1j*Z        #array([0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])
Z/1/1       #array([1., 2., 3., 4.])
Z<Z>Z       #ValueError

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [68]:
np.array(0) / np.array(0)                      #nan
np.array(0) // np.array(0)                     #0
np.array([np.nan]).astype(int).astype(float)   #array([-2.14748365e+09])

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [72]:
test = np.array([32.11, 51.5, 0.112, -20.5])
print(np.round(test,0))

[ 32.  52.   0. -20.]


#### 30. How to find common values between two arrays? (★☆☆)

In [75]:
print(np.intersect1d([1, 6, 9, 5, 7], [1, 3, 5]))

[1 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
#np.seterr(all="ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [76]:
np.sqrt(-1) == np.emath.sqrt(-1)  #False

C:\Users\Everest\AppData\Local\Temp\ipykernel_3840\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [77]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2022-10-23
Today:  2022-10-24
Tomorrow:  2022-10-25


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [78]:
print("July, 2016")
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

July, 2016
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [79]:
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [83]:
x = np.array([0.345, 2.423, 12.475, -1.525])
print(x)
x.astype(np.int32)
np.trunc(x)

[ 0.345  2.423 12.475 -1.525]


array([ 0.,  2., 12., -1.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [85]:
x = np.zeros((5,5))
print("Row values ranging from 0 to 4.")
x += np.arange(5)
print(x)

Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [88]:
def generate():
   for n in range(10):
       yield n
nums = np.fromiter(generate(),dtype=float,count=-1)
print("New array:")
print(nums)

New array:
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [91]:
x = np.linspace(0,1,12,endpoint=True)[1:-1]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [99]:
x = np.random.random(10)
x.sort()
print("Sorted array:")
print(x)

Sorted array:
[0.29970094 0.40626825 0.48999624 0.5594648  0.57821921 0.62059842
 0.63919767 0.79673818 0.82198814 0.94378017]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [100]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [104]:
A = np.random.randint(1,5,3)
B = np.random.randint(1,5,3)
print(A, B)
np.array_equal(A, B)

[3 3 3] [1 2 2]


False

#### 43. Make an array immutable (read-only) (★★☆)

In [105]:
a = np.random.random(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [106]:
z= np.random.random((10,2))
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[1.04441316 0.3474982  1.00933244 0.45831694 0.82295723 0.97129014
 1.24026122 0.68286863 1.39939036 0.60607915]
[1.11285142 1.18516872 1.41713846 0.83386832 0.15107957 0.84807048
 0.78034897 0.57110211 0.78177337 1.43031573]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [107]:
x = np.random.randint(10, 99, 10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[45 14 96 67 62 72 83 72 93 88]
Maximum value replaced by 0:
[45 14  0 67 62 72 83 72 93 88]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [109]:
z = np.zeros((5, 5), [('x', float), ('y', float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [110]:
x = np.random.random((5, 5))
y = np.random.random((5, 5))
c = 1 / (x - y)
c = 1 / np.subtract.outer(x, y)
np.linalg.det(c)

array([[ 7.43134940e+05,  1.49941221e+06, -2.33190958e+05,
        -2.89596839e+07,  3.22265679e+07],
       [ 1.14218345e+06,  8.64937764e+06, -1.60782709e+05,
         2.14025496e+04,  2.45026858e+06],
       [ 5.02959847e+04, -1.74411530e+04, -1.05253905e+04,
         3.21683769e+07, -5.62885085e+05],
       [-1.24015742e+09,  8.18027395e+04, -1.62664829e+05,
         1.30961297e+06, -1.32952608e+06],
       [ 1.02521368e+05, -1.32125418e+07,  1.26995649e+05,
        -6.55555314e+05,  7.33057444e+04]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [112]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [114]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [115]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

80


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [117]:
Z = np.zeros(10, [ ('position', [ ('x', float, (1,)),
                                  ('y', float, (1,))]),
                   ('color',    [ ('r', float, (1,)),
                                  ('g', float, (1,)),
                                  ('b', float, (1,))])])
print(Z)

[(([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [121]:
Z = np.random.randint(1, 10, (100,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         3.60555128 6.32455532 ... 3.         3.         7.21110255]
 [3.60555128 0.         3.         ... 3.16227766 2.         3.60555128]
 [6.32455532 3.         0.         ... 6.08276253 3.60555128 2.        ]
 ...
 [3.         3.16227766 6.08276253 ... 0.         4.24264069 6.08276253]
 [3.         2.         3.60555128 ... 4.24264069 0.         5.        ]
 [7.21110255 3.60555128 2.         ... 6.08276253 5.         0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [123]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[72 26 61 22 14 23 84 24 64 43]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [129]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int32)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [130]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [131]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [133]:
n = 4
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 1. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [139]:
print("Original matrix:\n")
X = np.random.randint(10, 99, (4,4))
print(X)
print("\nSubtract the mean of each row of a matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[63 27 56 93]
 [20 34 28 73]
 [21 65 38 43]
 [69 13 54 35]]

Subtract the mean of each row of a matrix:

[[  3.25 -32.75  -3.75  33.25]
 [-18.75  -4.75 -10.75  34.25]
 [-20.75  23.25  -3.75   1.25]
 [ 26.25 -29.75  11.25  -7.75]]


#### 59. How to sort an array by the nth column? (★★☆)

In [141]:
a = np.array([[9, 2, 3],[4, 5, 6],[7, 0, 5]])
a = a[a[:,0].argsort()] #sort by 1st column
print(a)

[[4 5 6]
 [7 0 5]
 [9 2 3]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [143]:
print("Original array:")
nums = np.random.randint(0,3,(4,10))
print(nums)
print("\nTest whether the said array has null columns or not:")
print((~nums.any(axis=0)).any())

Original array:
[[1 0 2 1 0 2 0 1 1 2]
 [0 2 1 1 2 1 0 2 0 0]
 [1 1 0 0 2 1 0 0 0 2]
 [0 1 2 0 1 2 1 1 2 1]]

Test whether the said array has null columns or not:
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [4]:
arr = np.random.randint(10,99,10)
print("Array is : ", arr)
x = 85
print("Value: ", x) 
difference_array = np.absolute(arr-x)
index = difference_array.argmin()
print("Nearest element to the given values is : ", arr[index])

Array is :  [44 15 28 71 59 46 37 96 83 19]
Value:  85
Nearest element to the given values is :  83


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [5]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [7]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [8]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 3. 2. 2. 1. 1. 3. 7. 1. 6.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [9]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [10]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [11]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.66980615 0.47173133 0.48551659 0.63726479 0.38183695 0.50228455
 0.3888605  0.45702108 0.48150458 0.53474868]


#### 69. How to get the diagonal of a dot product? (★★★)

In [21]:
A = np.random.randint(1,3,(4,4))
B = np.random.randint(1,3,(4,4))
np.diag(np.dot(A, B))

array([12,  7,  9,  9])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [13]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [14]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [17]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [18]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [23]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [29]:
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [30]:
Z = np.random.randint(0,2,100)
print ('original: ')
print (Z)
print('Negating a boolean: ')
print(np.logical_not(Z, out=Z))


Z = np.random.uniform(-1.0,1.0,10)
print ('original: ')
print (Z)
print ('Changed: ')
print(np.negative(Z, out=Z))

original: 
[0 0 0 0 1 0 0 1 1 0 0 1 0 1 1 1 0 1 1 1 1 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 0
 0 0 0 1 1 0 0 0 0 0 1 1 0 0 1 0 1 1 1 0 1 0 1 1 1 0 0 1 0 1 0 0 1 0 1 1 0
 1 0 0 0 0 1 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 1 1 0 0 1]
Negating a boolean: 
[1 1 1 1 0 1 1 0 0 1 1 0 1 0 0 0 1 0 0 0 0 1 0 0 1 1 1 0 1 1 1 1 0 0 1 1 1
 1 1 1 0 0 1 1 1 1 1 0 0 1 1 0 1 0 0 0 1 0 1 0 0 0 1 1 0 1 0 1 1 0 1 0 0 1
 0 1 1 1 1 0 1 1 1 1 0 0 1 1 0 1 1 0 1 1 1 0 0 1 1 0]
original: 
[ 0.37118801  0.84127942  0.94795718 -0.8777484  -0.56203632 -0.18052853
 -0.42980323  0.63256584  0.32263315  0.21426475]
Changed: 
[-0.37118801 -0.84127942 -0.94795718  0.8777484   0.56203632  0.18052853
  0.42980323 -0.63256584 -0.32263315 -0.21426475]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [31]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 0.9651693   5.48111915  1.04289208  3.26173606  5.90769997  0.45610228
 17.27629649  3.12548084 14.11219096 14.2906757 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [33]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 5.92675816  0.41610442  2.87695553  2.71939065  5.3162913   6.9015456
   2.59902252  6.9528513   0.97840229  3.54572699]
 [ 7.38562434  5.22984705 12.21255962  0.25356709  4.1824923   1.18743899
  12.22658485 11.9317981   7.18379326 10.47889779]
 [ 7.29320474  2.7098017   7.99844069  1.52132522  0.08438998  2.5917705
   8.34901021 10.28476665  4.11569138  7.13094228]
 [ 0.27224004  8.60540795 10.05412567  5.16399773  1.71611571  0.97007185
   3.94451597  3.01572288  9.20132388 11.69882296]
 [11.88205028  6.5968769   2.62076191  9.68091324 10.65857298 13.20369473
   2.56677629 11.24880465  5.88949216  3.16492926]
 [ 3.10817168  0.51696752  0.21553205  1.72967593  8.11292189  8.66509828
   2.1333206   2.98490799  0.34241344  2.49570446]
 [ 4.74069076  7.93531952 13.98501445  3.05230079  5.87807548  3.38292262
  11.63724083  9.77782825  9.73986744 12.92195501]
 [ 0.1840043   7.23932862  8.27745805  4.03703607  0.06451789  0.73504693
   2.71940917  2.84660339  7.67428457 10.09637009]
 [

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [40]:
Z = np.arange(1,15,dtype=int)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [43]:
Z = np.random.randint(1,10,(5,5))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
print(rank)

5


#### 83. How to find the most frequent value in an array?

In [47]:
Z = np.random.randint(1,10,10)
print(Z)
print("The most popular value: ", np.bincount(Z).argmax())

[2 2 2 2 4 3 7 4 6 6]
The most popular value:  2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [49]:
Z = np.random.randint(0,5,(10,10))
print(Z)
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[2 2 1 0 1 4 3 1 1 2]
 [0 4 4 1 3 4 4 2 2 3]
 [0 1 2 1 1 2 3 1 2 2]
 [2 0 1 3 4 2 2 1 0 2]
 [0 1 3 4 0 3 3 1 3 4]
 [3 0 1 4 2 2 4 4 3 2]
 [3 0 1 2 1 0 3 3 0 2]
 [1 0 3 0 0 3 3 1 0 2]
 [0 3 2 4 3 3 4 4 2 3]
 [1 3 0 2 2 3 4 0 2 1]]
[[[[2 2 1]
   [0 4 4]
   [0 1 2]]

  [[2 1 0]
   [4 4 1]
   [1 2 1]]

  [[1 0 1]
   [4 1 3]
   [2 1 1]]

  [[0 1 4]
   [1 3 4]
   [1 1 2]]

  [[1 4 3]
   [3 4 4]
   [1 2 3]]

  [[4 3 1]
   [4 4 2]
   [2 3 1]]

  [[3 1 1]
   [4 2 2]
   [3 1 2]]

  [[1 1 2]
   [2 2 3]
   [1 2 2]]]


 [[[0 4 4]
   [0 1 2]
   [2 0 1]]

  [[4 4 1]
   [1 2 1]
   [0 1 3]]

  [[4 1 3]
   [2 1 1]
   [1 3 4]]

  [[1 3 4]
   [1 1 2]
   [3 4 2]]

  [[3 4 4]
   [1 2 3]
   [4 2 2]]

  [[4 4 2]
   [2 3 1]
   [2 2 1]]

  [[4 2 2]
   [3 1 2]
   [2 1 0]]

  [[2 2 3]
   [1 2 2]
   [1 0 2]]]


 [[[0 1 2]
   [2 0 1]
   [0 1 3]]

  [[1 2 1]
   [0 1 3]
   [1 3 4]]

  [[2 1 1]
   [1 3 4]
   [3 4 0]]

  [[1 1 2]
   [3 4 2]
   [4 0 3]]

  [[1 2 3]
   [4 2 2]
   [0 3 3]]

  [[2 3 1]
   [2 2 1]
   [3 3 

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [51]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0  4  8  6  7]
 [ 4  2  9 18 11]
 [ 8  9  0 42  4]
 [ 6 18 42  8  8]
 [ 7 11  4  8  4]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [53]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [55]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [57]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [61]:
Z = np.random.randint(1,20,10)
print(Z)
n = 3
print (Z[np.argsort(Z)[-n:]])

[ 4  6 10 16  4 19 14 13 13  3]
[14 16 19]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [62]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [64]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [67]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.49 s ± 33 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
359 ms ± 7.11 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
198 ms ± 24.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [97]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
print("A: \n", A)
print("B: \n", B)
C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print("Rows: \n", rows)

A: 
 [[1 3 4]
 [1 2 0]
 [3 1 4]
 [0 2 0]
 [0 3 3]
 [0 0 4]
 [0 0 2]
 [0 3 2]]
B: 
 [[0 1]
 [3 0]]
Rows: 
 [0 1 2 3 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [96]:
Z = np.random.randint(0,2,(10,3))
print(Z)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print("Rows with unequal values: \n", U)

[[0 1 0]
 [1 1 1]
 [1 1 1]
 [0 1 1]
 [1 0 0]
 [0 0 1]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [0 1 0]]
Rows with unequal values: 
 [[0 1 0]
 [0 1 1]
 [1 0 0]
 [0 0 1]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [0 1 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [76]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [95]:
Z = np.random.randint(0,2,(6,3))
print(Z)
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print("Unique rows: \n", uZ)

[[0 1 1]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [0 0 1]
 [0 0 1]]
Unique rows: 
 [[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [93]:
A = np.random.randint(1,10,5)
B = np.random.randint(1,10,5)
print(A, B)
print("Sum A: ", np.einsum('i->', A)) # np.sum(A)
print("A * B:", np.einsum('i,i->i', A, B)) # A * B
print("Inner: ", np.einsum('i,i', A, B)) # np.inner(A, B)
print("Outer: \n", np.einsum('i,j', A, B)) # np.outer(A, B)

[2 5 9 7 6] [3 5 4 5 3]
Sum A:  29
A * B: [ 6 25 36 35 18]
Inner:  120
Outer: 
 [[ 6 10  8 10  6]
 [15 25 20 25 15]
 [27 45 36 45 27]
 [21 35 28 35 21]
 [18 30 24 30 18]]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [98]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [99]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
[2.0, 0.0, 1.0, 1.0],
[1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [102]:
X = np.random.randint(1, 10, 100) 
N = 100 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[4.5595 5.551 ]
