# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [65]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [66]:
print(np.__version__)
print(np.show_config())

1.23.1
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Miniconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Miniconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Miniconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Miniconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Miniconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Miniconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Miniconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/

#### 3. Create a null vector of sivectore 10 (★☆☆)

In [67]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory sivectore of any array (★☆☆)

In [68]:
memory_size_null_vector=null_vector.size*null_vector.itemsize
print(memory_size_null_vector)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [69]:
!python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of sivectore 10 but the fifth value which is 1 (★☆☆)

In [70]:
vector = np.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [71]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [72]:
vector=vector[::-1]
print(vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [73]:
vector=np.arange(9).reshape(3,3)
print(vector)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-vectorero elements from [1,2,0,0,4,0] (★☆☆)

In [74]:
non_zero_indexes = np.nonzero([0,1,1,1])
print(non_zero_indexes)

(array([1, 2, 3], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [75]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [76]:
vector = np.random.random((3,3,3))
print(vector)

[[[0.12139209 0.38402054 0.81773127]
  [0.63444964 0.44811014 0.32003183]
  [0.22329716 0.44058677 0.26547904]]

 [[0.25828428 0.79252817 0.58065188]
  [0.87572232 0.30843011 0.86289811]
  [0.54517153 0.78386031 0.23311233]]

 [[0.51859712 0.08407136 0.69645306]
  [0.48728715 0.29555834 0.60391442]
  [0.89084702 0.64279763 0.44647925]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [77]:
vector_min, vector_max = vector.min(), vector.max()
print(vector_min, vector_max)

0.08407135710731506 0.8908470248508442


#### 14. Create a random vector of sivectore 30 and find the mean value (★☆☆)

In [78]:
vector = np.random.random(30);
print(vector.mean())

0.5129315731687313


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [79]:
vector=np.ones((3,3))
vector[1:-1,1:-1] = 0
print(vector)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [80]:
vector = np.ones((2,2))
vector = np.pad(vector, pad_width=1, mode='constant', constant_values=0)
print(vector)

[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [81]:
NaN
False
False
nan
True
False

NameError: name 'NaN' is not defined

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
print(np.diag(1+np.arange(4),k=-1))

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
checkerboard = np.zeros((8,8),dtype=int)
checkerboard[1::2,::2] = 1
checkerboard[::2,1::2] = 1
print(checkerboard)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,vector) of the 100th element? (★☆☆)

In [ ]:
print(np.unravel_index(100,(6,7,8)))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
checkerboard = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(checkerboard)

#### 22. Normalivectore a 5x5 random matrix (★☆☆)

In [ ]:
matrix = np.random.random((5,5))
matrix  = (matrix  - np.mean (matrix)) / (np.std (matrix))
print(vector)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
custom_dtype = np.dtype([
    ('r',np.ubyte,1),
    ('g', np.ubyte, 1),
    ('b', np.ubyte, 1),
    ('a', np.ubyte, 1)])
print(custom_dtype)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
multiply_matrix = np.dot(np.ones((5,3)),np.ones((3,2)))
print(multiply_matrix)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
_1d_array = np.arange(11)
_1d_array[(3<_1d_array)&(_1d_array<=8)]*=-1
print(_1d_array)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
vector=np.zeros(10);
vector=np.random.uniform(-1,+1,10)
np.copysign(np.ceil(np.abs(vector)),vector)

#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
arr1 = [1,2,3,4,5]
arr2=[5,7,5,3,2]
np.intersect1d(arr1,arr2)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
#np.seterr(all="ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
july_days = np.arange('2016-07','2016-08',dtype='datetime64[D]')
july_days

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = 2
B= 4
np.multiply(np.add(A,B),(np.divide(np.negative(A),2)))

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
vector=np.random.uniform(0,10,10)

print (vector - vector%1)
print (np.floor(vector))
print (np.ceil(vector)-1)
print (vector.astype(int))
print (np.trunc(vector))

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
vector = np.zeros((5,5))
vector += np.arange(5)
print(vector)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generator():
    for x in range(10):
        yield x
vector = np.fromiter(generator(),dtype=float,count=-1)
print(vector)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
vector = np.linspace(0,1,11,endpoint=False)[1:]
print(vector)

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
vector = np.random.random(10)
vector.sort()
vector

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
vector = np.arange(10)
np.add.reduce(vector)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = [1,2,3]
B  = [1,2,4]

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
vector.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
vector = np.random.random((10,2))
X,Y = vector[:,0], vector[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
vector = np.array([1,2,3,4])
vector[vector.argmax()] = 0
print(vector)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
vector = np.zeros((5,5), [('x',float),('y',float)])
vector['x'], vector['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(vector)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

#### 49. How to print all the values of an array? (★★☆)

In [ ]:
np.set_printoptions(threshold=0)
matrix = np.zeros((4,4))
print(matrix)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
vector = np.arange(100)

num = np.random.uniform(0,100);

index = (np.abs(vector-num)).argmin()
print(vector[index])


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:


array = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(array)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
vector = np.random.random((100,2))
X,Y = np.atleast_2d(vector[:,0], vector[:,1])
distance = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)

print(distance)


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:

array = np.arange(5, dtype=np.float32)
print(array)
array = array.astype(np.int32, copy=False)
print(array)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
file = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
matrix = np.genfromtxt(file, delimiter=",", dtype=int)
matrix

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:

matrix = np.arange(4).reshape(2,2)
for index, value in np.ndenumerate(matrix):
    print(index, value)

print('--------')
for index in np.ndindex(matrix.shape):
        print(index, matrix[index])

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,3), np.linspace(-1,1,3))

D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
N = 4
p = 1
matrix = np.zeros((N,N))
np.put(matrix, np.random.choice(range(N*N), p, replace=False),1)
print(matrix)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
X = np.random.rand(2, 2)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
matrix = np.random.randint(0,10,(3,3))
print(matrix)
print(matrix[matrix[:,1].argsort()])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
array = np.random.randint(0,1,(3,3))
print (array)
print((~array.any(axis=0)).any())

#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
array = np.random.uniform(0,1,10)
print(array)
given_value = 0.9
nearest_value = array.flat[np.abs(array - given_value).argmin()]
print(nearest_value)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
array1 = np.arange(3).reshape(3,1)
print(array1)
array2 = np.arange(3).reshape(1,3)
print(array2)
it = np.nditer([array1,array2,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class MyArray(np.ndarray):
    def __new__(cls, array, name="empty"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "empty")
arr = MyArray(np.arange(3),'123');
print(arr.name)


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
vector = np.ones(10)
I = np.random.randint(0,len(vector),20)
np.add.at(vector, I, 1)
print(vector)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:

vector = [1,2,3,4,5,6]
index_list = [5,4,3,2,1,0]
array = np.bincount(index_list,vector)
print(array)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
width,height = 16,16
I = np.random.randint(0,2,(height,width,3)).astype(np.ubyte)
print(I)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
print(F)

n = len(np.unique(F))
print(n)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
array4D = np.random.randint(0,4,(3,2,3,2))
sum = array4D.sum(axis=(-2,-1))
print(sum)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
import pandas as pd;
vector1D = np.random.uniform(0,1,10);
print(vector1D)
S = np.random.randint(0,10,10)
print(S)
print(pd.Series(vector1D).groupby(S).mean()

#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.random.uniform(0,1,(3,3))
B = np.random.uniform(0,1,(3,3)) 
np.diag(np.dot(A, B))

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
vector = np.array([1,2,3,4,5])
numberOfZeros = 3
vector_zeros = np.zeros(len(vector) + (len(vector)-1)*(numberOfZeros))
vector_zeros[::numberOfZeros+1] = vector
print(vector_zeros)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
array1 = np.ones((5,5,3))
array2 = 2*np.ones((5,5))
print(array1 * array2[:,:,None])

#### 72. How to swap two rows of an array? (★★★)

In [ ]:
array = np.arange(9).reshape(3,3)
array[[0,1]] = array[[1,0]]
print(array)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
setOfTriplets = np.random.randint(0,100,(10,3))
F = np.roll(setOfTriplets.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
setOfUnique = np.unique(G)
print(setOfUnique)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
C = np.bincount([1,2,3,4,5])
A = np.repeat(np.arange(len(C)), C)
print(np.bincount(A) == C)

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
def func_75(a, n) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
array = np.arange(10)
print(func_75(array, n=3))

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
from numpy.lib import stride_tricks
def func_76(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
arrayZ = func_76(np.arange(10), 3)
print(arrayZ)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
rray = np.random.randint(0,2,100)
print(array)
array=np.logical_not(array, out=array)
print(array)

array = np.random.uniform(-1.0,1.0,100)
print(array)
np.negative(array, out=array)
print(array)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
def distanceFromP(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(3,2))
P1 = np.random.uniform(-10,10,(3,2))
p  = np.random.uniform(-10,10,( 1,2))

print(P0)
print(P1)
print(p)
print(distanceFromP(P0, P1, p))

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
def distanceFromP(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10, 10, (3,2))
P1 = np.random.uniform(-10,10,(3,2))
p = np.random.uniform(-10, 10, (2,2))
print(np.array([distanceFromP(P0,P1,p_i) for p_i in p]))

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
array = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=array.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
arrays = np.array(list(array.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
array_start = (P-Rs//2)
array_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(array_start,0)).tolist()
array_start = (np.maximum(array_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(array_stop-arrays,0))).tolist()
array_stop = (np.minimum(array_stop,arrays)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(array_start,array_stop)]
R[r] = array[z]
print(array)
print(R)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
from numpy.lib import stride_tricks
array = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(array,(11,4),(4,4))
print(R)

#### 82. Compute a matrix rank (★★★)

In [ ]:
M = np.random.uniform(0,1,(5,5))
print(M)
U, S, V = np.linalg.svd(M)
rank = np.sum(S > 1e-10)
print(rank)

#### 83. How to find the most frequent value in an array?

In [ ]:
array = np.random.randint(0,10,50)
print(np.bincount(array).argmax())

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
array = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (array.shape[0]-3)
j = 1 + (array.shape[1]-3)
C = stride_tricks.as_strided(array, shape=(i, j, n, n), strides=array.strides + array.strides)
print(C)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
class Sym(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Sym, self).__setitem__((i,j), value)
        super(Sym, self).__setitem__((j,i), value)

def symetric(x):
    return np.asarray(x + x.T - np.diag(x.diagonal())).view(Sym)

S = symetric(np.random.randint(0,5,(6,6)))
S[2,3] = 42
print(S)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
array = np.ones((16,16))
k = 4
sum = np.add.reduceat(np.add.reduceat(array, np.arange(0, array.shape[0], k), axis=0),
                                       np.arange(0, array.shape[1], k), axis=1)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(array):
    
    N = (array[0:-2, 0:-2] + array[0:-2, 1:-1] + array[0:-2, 2:] +
         array[1:-1, 0:-2] + array[1:-1, 2:] +
         array[2:, 0:-2] + array[2:, 1:-1] + array[2:, 2:])

    
    birth = (N == 3) & (array[1:-1, 1:-1] == 0)
    survive = ((N == 2) | (N == 3)) & (array[1:-1, 1:-1] == 1)
    array[...] = 0
    array[1:-1, 1:-1][birth | survive] = 1
    return array


array = np.random.randint(0, 2, (50, 50))
for i in range(100): array = iterate(array)
print(array)


#### 89. How to get the n largest values of an array (★★★)

In [ ]:

array = np.arange(1000)
np.random.shuffle(array)
n = 3

print(array[np.argsort(array)[-n:]])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
def build_cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (build_cartesian(([1, 2, 3], [4, 5], [6, 7])))

#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
array = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
result = np.core.records.fromarrays(array.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
result

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
x = np.random.rand(123)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
array_A = np.random.randint(0,5,(8,3))
array_B = np.random.randint(0,5,(2,2))

array_C = (array_A[..., np.newaxis, np.newaxis] == array_B)
rows = np.where(array_C.any((3,1)).all(1))[0]
print(rows)


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
array = np.random.randint(0,5,(10,3))
print(array)

result = array[array.max(axis=1) != array.min(axis=1),:]
print(result)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
vector = np.array([1,3,4,2,5,7,8], dtype=np.uint8)
print(np.unpackbits(vector[:, np.newaxis], axis=1))

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
array=np.random.randint(0,2,(8,5))
print(array)
result = np.unique(array, axis=0)
print(result)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:

A = np.random.uniform(0,1,5)
B = np.random.uniform(0,1,5)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B) 
np.einsum('i,j->ij', A, B)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
F = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*F*np.cos(F)
y = a*F*np.sin(F)

diff_r = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(diff_r)             
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)      
y_int = np.interp(r_int, r, y)


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
array = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(array, 1) == 0, axis=-1)
M &= (array.sum(axis=-1) == n)
print(array[M])

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
array = np.random.randn(100)
bootstrap_samples = 1000
idx = np.random.randint(0, array.size, (bootstrap_samples, array.size))
means = array[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)