# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)

1.23.3


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
coords = []
for i in range(10):
    coords.append(0)

null_vector = np.array(coords)

print(null_vector)

#or

null_vector_2 = np.zeros(10)
print(null_vector_2)

[0 0 0 0 0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
print(null_vector.size * null_vector.itemsize)

40


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
coords.clear()
for i in range(10):
    coords.append(0 if i != 4 else 1)

null_vector = np.array(coords)

print(null_vector)

[0 0 0 0 1 0 0 0 0 0]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
random_array = np.linspace(10, 49, 10, dtype = int)
print(random_array)

random_array = np.arange(10, 49, 1)
print(random_array)

[10 14 18 23 27 31 36 40 44 49]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
rev_vector = np.array([0,1,2,3,4,5,6,7,8,9])
print(np.flip(rev_vector))

[9 8 7 6 5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
matrix = np.arange(0,9,1)
matrix.shape = (3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
nums = np.array([1,2,0,0,4,0])
indices = np.where(nums != 0)

print(indices[0])

[0 1 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
print(np.random.randint(0, 9, size=(3,3,3)))

[[[2 6 3]
  [3 7 1]
  [1 2 5]]

 [[5 1 6]
  [1 4 6]
  [0 2 7]]

 [[0 8 2]
  [0 5 8]
  [4 8 2]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
matrix = np.random.randint(0, 1001, size=(10, 10))

min = np.min(matrix)
max = np.max(matrix)

print(f"Matrix:\n{matrix}\nMin: {min}\nMax: {max}\n")

Matrix:
[[573 283 132 685 145 731 499 439 917 796]
 [347 952 176 645 485  94 781  91 132 949]
 [823 429 833  58  19 824  35 243 287 789]
 [338 581 454 297 932 220 481 725 349 512]
 [228 197 172 312 311 898 317 642 738 355]
 [ 51  39 551 846 681 803 686 708 383 974]
 [694 343  62 385 994 772 199  48 548 499]
 [817 250 977  99 465  68 622 753  28 592]
 [735  44 117 677 421 103 845 335 562 730]
 [435  99 215 604 686  72 696  56 233  60]]
Min: 19
Max: 994



#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
rand_vector = np.random.randint(0, 1001, 30)
print(f"{rand_vector}\n{np.mean(rand_vector)}")

[968 265 146  84 110  87 953 925 641 683 903 298 485 249 723 890  43 925
 111 494 386 753 969 344 388 705 559 152 455 540]
507.8


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
square_matrix = np.zeros((5,5))
square_matrix[:, 0] = 1
square_matrix[0, :] = 1
square_matrix[:, square_matrix[0].shape[0] - 1] = 1
square_matrix[square_matrix.shape[1] - 1, :] = 1
print(square_matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
square_matrix = np.pad(square_matrix, 1, constant_values=0)
print(square_matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
some_new_matrix = np.diag(np.arange(1, 5, 1), k = -1)

print(some_new_matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
checkerboard = np.ones((8,8))
checkerboard[0:checkerboard.shape[0]:2,::2] = 0
checkerboard[1::2, 1:checkerboard.shape[0]:2] = 0
print(checkerboard)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [21]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
print(np.tile(np.array([[0,1],[1,0]]), (4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
rand_matrix = np.random.randint(0, 100, size=(5, 5))
print(rand_matrix)
matrix_max = rand_matrix.max()
matrix_min = rand_matrix.min()
matrix_normalized = (rand_matrix - matrix_max)/(matrix_max - matrix_min)
print(matrix_normalized)

[[72 81 58 96 27]
 [41 39 73 76 54]
 [47 98 12 91 24]
 [76 87 10 88 49]
 [ 4 74  1 10 32]]
[[-0.26804124 -0.17525773 -0.41237113 -0.02061856 -0.73195876]
 [-0.58762887 -0.60824742 -0.25773196 -0.22680412 -0.45360825]
 [-0.5257732   0.         -0.88659794 -0.07216495 -0.7628866 ]
 [-0.22680412 -0.11340206 -0.90721649 -0.10309278 -0.50515464]
 [-0.96907216 -0.24742268 -1.         -0.90721649 -0.68041237]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
rgba = np.dtype({'names': ['r','g','b','a'], 'formats': [np.uint8, np.uint8, np.uint8, np.uint8]})
color = np.array([(255, 188, 32, 55)], dtype=rgba)
print(color)

[(255, 188, 32, 55)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
mat_A = np.random.randint(0, 30, size=(5, 3))
mat_B = np.random.randint(0, 30, size=(3, 2))

print(mat_A.dot(mat_B))

[[ 537  466]
 [1102  756]
 [ 574  470]
 [1533 1098]
 [1328  914]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
neg_array = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
neg_array[(neg_array > 3) & (neg_array < 8)] *= -1

print(neg_array)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
9
10

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1

NameError: name 'Z' is not defined

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
#invalid value encountered in divide
#divide by zero
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [30]:
array = np.array([1.34,2.44,3.22,4.44,5.55])
round_arr = np.round(array)
print(round_arr)

[1. 2. 3. 4. 6.]


#### 30. How to find common values between two arrays? (★☆☆)

In [31]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([5,6,7,8,9,10])

print(np.intersect1d(arr1, arr2))

[5 6]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [32]:
#np.seterr(all="ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [33]:
#no

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [34]:
today = np.datetime64('today')
yesterday = np.datetime64('today') - np.timedelta64(1, 'D')
tomorrow = np.datetime64('today') + np.timedelta64(1, 'D')

print(f"today: {today}\nyesterday: {yesterday}\ntomorrow: {tomorrow}\n")

today: 2022-10-29
yesterday: 2022-10-28
tomorrow: 2022-10-30



#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [35]:
print("July 2016")
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

July 2016
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [36]:
mat_A = np.random.randint(0, 30, size=(5, 5))
mat_B = np.random.randint(0, 30, size=(5, 5))

print(np.add(mat_A, mat_B).dot(-mat_A / 2))

[[ -936.5  -918.  -1218.5 -1190.   -985. ]
 [-1000.   -978.  -1129.5  -960.5 -1021.5]
 [ -972.   -954.  -1040.   -912.   -910. ]
 [-1002.  -1258.5 -1560.  -1327.5 -1294. ]
 [-1086.   -933.  -1249.5 -1203.   -951. ]]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [37]:
arr = np.random.randint(0, 30, 36)

print(np.floor(arr))
print(np.ceil(arr)-1)
print(np.trunc(arr))
print(arr.astype(int))
print(arr - arr%1)

[ 3. 28. 27. 21.  7. 28. 28. 17.  1.  4. 10. 15. 20. 26.  5. 17.  6. 24.
  7. 20. 27. 29.  0.  0. 13.  4. 24. 28. 12. 11. 29. 13. 19. 13.  1.  9.]
[ 2. 27. 26. 20.  6. 27. 27. 16.  0.  3.  9. 14. 19. 25.  4. 16.  5. 23.
  6. 19. 26. 28. -1. -1. 12.  3. 23. 27. 11. 10. 28. 12. 18. 12.  0.  8.]
[ 3. 28. 27. 21.  7. 28. 28. 17.  1.  4. 10. 15. 20. 26.  5. 17.  6. 24.
  7. 20. 27. 29.  0.  0. 13.  4. 24. 28. 12. 11. 29. 13. 19. 13.  1.  9.]
[ 3 28 27 21  7 28 28 17  1  4 10 15 20 26  5 17  6 24  7 20 27 29  0  0
 13  4 24 28 12 11 29 13 19 13  1  9]
[ 3 28 27 21  7 28 28 17  1  4 10 15 20 26  5 17  6 24  7 20 27 29  0  0
 13  4 24 28 12 11 29 13 19 13  1  9]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [38]:
print(np.tile(np.arange(5), (5,1)))

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [39]:
def generate(size):
    for i in range(size):
        yield i
        
array = np.fromiter(generate(10),dtype=int)
print(array)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [40]:
vector = np.linspace(0,1,11,endpoint=False)[1:]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [41]:
vector = np.random.randint(0, 30, 10)
vector.sort()
print(vector)

[ 3  6 11 13 14 20 23 26 26 29]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [42]:
A = np.random.randint(0, 30, 10)
B = np.random.randint(0, 30, 10)

print(np.array_equal(A,B))

A = np.array([7,2,3,4,1])
B = np.array([7,2,3,4,1])

print(np.array_equal(A,B))

False
True


#### 43. Make an array immutable (read-only) (★★☆)

In [43]:
read_only = np.random.randint(0, 30, 10)
read_only.flags.writeable = False
read_only[0] = 15

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [44]:
cartesian_coords = np.random.random((10,2))

x_coords = cartesian_coords[:,0]
y_coords = cartesian_coords[:,1]

r_coords = np.sqrt(x_coords ** 2 + y_coords ** 2)
theta_coords = np.arctan2(y_coords,x_coords)

print(f"r: {r_coords}\n\ntheta:{theta_coords}")

r: [1.16379515 0.64110364 0.87337485 0.79619933 0.55830304 0.58117672
 0.99057989 0.24297776 0.96414778 0.85638304]

theta:[0.68302587 1.47486303 0.3096865  1.50052264 0.73707379 0.63401259
 0.685568   0.89384204 0.88794195 0.27910179]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [45]:
vector = np.random.randint(0, 30, 10)

print(vector)

vector[np.where(vector == vector.max())] = 0

print(vector)

[ 7 21  8 16 18 16  5  9 26 27]
[ 7 21  8 16 18 16  5  9 26  0]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [46]:
coords = np.zeros((5,5), [('x',float),('y',float)])

coords['x'], coords['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(coords)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [47]:
X_arr = np.random.randint(0, 30, 10)
Y_arr = np.random.randint(0, 30, 10)

X_arr = X_arr.reshape((-1,1))

diff_matrix = X_arr - Y_arr

cauchy_matrix = 1.0 / diff_matrix
print(cauchy_matrix)

[[        inf -0.33333333  0.33333333  0.16666667  0.04761905  0.04
   0.09090909  0.2         0.11111111  0.33333333]
 [        inf -0.33333333  0.33333333  0.16666667  0.04761905  0.04
   0.09090909  0.2         0.11111111  0.33333333]
 [        inf -0.33333333  0.33333333  0.16666667  0.04761905  0.04
   0.09090909  0.2         0.11111111  0.33333333]
 [-0.33333333 -0.16666667         inf  0.33333333  0.05555556  0.04545455
   0.125       0.5         0.16666667         inf]
 [-0.125      -0.09090909 -0.2        -0.5         0.07692308  0.05882353
   0.33333333 -0.33333333  1.         -0.2       ]
 [-0.03846154 -0.03448276 -0.04347826 -0.05       -0.2        -1.
  -0.06666667 -0.04761905 -0.05882353 -0.04347826]
 [-0.05       -0.04347826 -0.05882353 -0.07142857  1.          0.2
  -0.11111111 -0.06666667 -0.09090909 -0.05882353]
 [-0.07142857 -0.05882353 -0.09090909 -0.125       0.14285714  0.09090909
  -0.33333333 -0.11111111 -0.2        -0.09090909]
 [-0.1        -0.07692308 -0.1428

C:\Users\Vitalii\AppData\Local\Temp\ipykernel_12016\338302039.py:8: RuntimeWarning: divide by zero encountered in divide
  cauchy_matrix = 1.0 / diff_matrix


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [48]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [49]:
array = np.random.randint(0, 30, 10)
print(array)

[27 27 14 24  3  5  2 18 13  4]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [50]:
vector = np.random.randint(0, 30, 10)
scalar = np.random.randint(30)

index = (np.abs(vector-scalar)).argmin()
print(f"Closest value to scalar: {scalar} is value: {vector[index]} with index: {index} from vector:\n{vector}")

Closest value to scalar: 11 is value: 12 with index: 5 from vector:
[26  8  8  8  0 12 25 28 13 29]


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [51]:
rgb_pos_dt = np.dtype([
    ('position', [ 
        ('x', 'f4'),
        ('y', 'f4')
    ]),
    ('color', [
        ('r', 'u1'),
        ('g', 'u1'),
        ('b', 'u1')
    ])
])


matrix = np.zeros((6,3), rgb_pos_dt)
print(matrix)

[[((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))]
 [((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))]
 [((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))]
 [((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))]
 [((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))]
 [((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))]]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [53]:
vector = np.random.random((100,2))

x, y = np.atleast_2d(vector[:,0], vector[:,1])
distance = np.sqrt( (x-x.T)**2 + (y-y.T)**2)

print(distance)


[[0.         0.25239588 0.68815746 ... 0.73305044 0.45297062 0.68155424]
 [0.25239588 0.         0.83519423 ... 0.97669069 0.64149381 0.84076743]
 [0.68815746 0.83519423 0.         ... 0.54538414 0.96520224 0.04598974]
 ...
 [0.73305044 0.97669069 0.54538414 ... 0.         0.70982809 0.4998806 ]
 [0.45297062 0.64149381 0.96520224 ... 0.70982809 0.         0.93920454]
 [0.68155424 0.84076743 0.04598974 ... 0.4998806  0.93920454 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [58]:
array = np.arange(10, dtype=np.float32)

array = array.astype(np.int32, copy=False)

print(array)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [56]:
from io import StringIO


some_file = StringIO("""1, 2, 3, 4, 5\n
                        6,  ,  , 7, 8\n
                         ,  , 9,10,11\n""")

imported_array = np.genfromtxt(some_file, delimiter=",", dtype=int)
print(imported_array)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [61]:
matrix = np.random.randint(0, 30, size=(3,3))

for index, value in np.ndenumerate(matrix):
    print(index, value)
    
for index in np.ndindex(matrix.shape):
    print(index, matrix[index])

(0, 0) 15
(0, 1) 13
(0, 2) 23
(1, 0) 5
(1, 1) 2
(1, 2) 1
(2, 0) 26
(2, 1) 4
(2, 2) 10
(0, 0) 15
(0, 1) 13
(0, 2) 23
(1, 0) 5
(1, 1) 2
(1, 2) 1
(2, 0) 26
(2, 1) 4
(2, 2) 10


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [63]:
x, y = np.meshgrid(np.random.random(10), np.random.random(10))

sigma = 1.0 
mu = 0.0

gaussian = np.exp(-((np.sqrt(x*x+y*y)-mu)**2/(2.0 * sigma**2)))
print(gaussian)



[[0.98901559 0.90076394 0.98697253 0.77852676 0.99090496 0.95036558
  0.9879861  0.74651512 0.61955304 0.88745393]
 [0.6550139  0.59656582 0.6536608  0.51560951 0.65626521 0.62941643
  0.65433208 0.49440856 0.410323   0.58775075]
 [0.92157954 0.83934533 0.91967578 0.72544289 0.92334008 0.88556487
  0.92062024 0.69561396 0.5773088  0.82694285]
 [0.8992835  0.81903881 0.89742581 0.70789205 0.90100145 0.86414016
  0.89834742 0.67878478 0.5633418  0.8069364 ]
 [0.90754037 0.82655891 0.90566562 0.71439163 0.9092741  0.87207435
  0.90659569 0.68501712 0.56851419 0.81434537]
 [0.98675771 0.89870754 0.98471932 0.77674942 0.98864277 0.94819594
  0.98573057 0.74481086 0.61813863 0.88542791]
 [0.88362493 0.80477748 0.88179958 0.69556604 0.88531297 0.84909351
  0.88270515 0.66696559 0.55353274 0.7928858 ]
 [0.86878765 0.79126416 0.86699295 0.68388652 0.87044734 0.83483606
  0.86788331 0.65576632 0.54423816 0.77957215]
 [0.94595654 0.86154713 0.94400243 0.74463182 0.94776365 0.90898924
  0.94497187

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [67]:
matrix = np.zeros((10,10))
count_of_replacements = 1
replacer_num = 7
np.put(matrix, np.random.choice(matrix.size, count_of_replacements, replace=False), replacer_num)
print(matrix)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 7. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [69]:
matrix = np.random.randint(0, 30, size=(5,10))
mean = matrix - matrix.mean(axis=1, keepdims=True)

print(mean)

[[ -1.5  -6.5  -3.5   8.5   9.5  -3.5   8.5 -12.5   9.5  -8.5]
 [  3.6   4.6 -11.4  -0.4   4.6  -2.4 -11.4  -2.4   9.6   5.6]
 [ -5.2 -15.2  -3.2  -4.2  11.8   4.8  -2.2   4.8  11.8  -3.2]
 [ -5.4  14.6  -8.4   2.6   8.6   6.6   0.6  -2.4  -5.4 -11.4]
 [ 10.1  12.1  -1.9   3.1  -9.9  -0.9  -8.9   1.1  -1.9  -2.9]]


#### 59. How to sort an array by the nth column? (★★☆)

In [70]:
matrix = np.random.randint(0,30,(3,3))
print(matrix)
print(matrix[matrix[:,1].argsort()])

[[ 8  7  0]
 [12 29 15]
 [18  3 20]]
[[18  3 20]
 [ 8  7  0]
 [12 29 15]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [77]:
matrix = np.random.randint(0,3,(3,10))
print(matrix)
print((~matrix.any(axis=0)).any())

[[0 2 2 2 2 0 1 1 1 1]
 [1 2 0 0 2 0 2 1 0 1]
 [1 2 2 0 1 0 0 1 0 1]]
True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [80]:
array = np.random.randint(0,345,30)
value = 8
m = array.flat[np.abs(array - value).argmin()]
print(array)
print(m)

[  6 248  78 311 127   2 218 321 119  29 152  15 126 175 255 270 139 151
 247 273   7 158  48 256  87 220 112   3 261 178]
7


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [81]:
arr_1 = np.random.randint(0,10,(1,3))
arr_2 = np.random.randint(0,10,(3,1))

iterator = np.nditer([arr_1, arr_2, None])

for x,y,z in iterator: z[...] = x + y

print(iterator.operands[2])

[[ 1  4  8]
 [ 9 12 16]
 [ 2  5  9]]


#### 63. Create an array class that has a name attribute (★★☆)

In [88]:
class NamedArray(np.ndarray):
    def __init__(self, array, name="no name"):
        self.array = array
        self.name = name
        
named_array = NamedArray(np.random.randint(0,10,30), "name")

print(f"Name: {named_array.name}: {named_array}")


TypeError: data type 'name' not understood

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)