# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/alina.riabushenko/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/alina.riabushenko/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/alina.riabushenko/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/alina.riabushenko/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/alina.riabushenko/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/alina.riabushenko/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/alina.riabushenko/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/alina.riabu

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
nullVec = np.zeros(10)
nullVec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
#help(np.ndarray)
nullVec.nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
np.add.__doc__

"add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])\n\nAdd arguments element-wise.\n\nParameters\n----------\nx1, x2 : array_like\n    The arrays to be added.\n    If ``x1.shape != x2.shape``, they must be broadcastable to a common\n    shape (which becomes the shape of the output).\nout : ndarray, None, or tuple of ndarray and None, optional\n    A location into which the result is stored. If provided, it must have\n    a shape that the inputs broadcast to. If not provided or None,\n    a freshly-allocated array is returned. A tuple (possible only as a\n    keyword argument) must have length equal to the number of outputs.\nwhere : array_like, optional\n    This condition is broadcast over the input. At locations where the\n    condition is True, the `out` array will be set to the ufunc result.\n    Elsewhere, the `out` array will retain its original value.\n    Note that if an uninitialized `out` array is created via t

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
nullVec = np.zeros(10, dtype=np.int64)
nullVec[4] = 1
nullVec

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
vector = np.arange(10, 50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
reversed = np.flip(vector)
reversed

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
matrix = np.arange(9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
array = np.array([1,2,0,0,4,0])
array.nonzero()[0]

array([0, 1, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
idMat = np.eye(3)
idMat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
rng = np.random.default_rng()
tensor = rng.random((3,3,3))
tensor

array([[[0.13677137, 0.94591007, 0.3411896 ],
        [0.24802569, 0.55244426, 0.10078588],
        [0.44960217, 0.5895186 , 0.23315961]],

       [[0.5800167 , 0.87030546, 0.11869607],
        [0.87891213, 0.23679079, 0.68844577],
        [0.44077956, 0.94710368, 0.42302493]],

       [[0.46747312, 0.91029286, 0.81059893],
        [0.42775011, 0.63440166, 0.35245973],
        [0.95239829, 0.45901538, 0.69201835]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [17]:
mat2d = rng.integers(100, size=(10, 10))
print(mat2d)
print(f"maximum: {mat2d.max()} minimum: {mat2d.min()}")

[[85 33 19 37 34 28 32 40 88 14]
 [89 89 25 43 91 80 12 30  9 17]
 [58 22 57 88 37 14 62 63 62 48]
 [37  5 71 45 22 13 57 22 63  7]
 [79 39 38 23  0 91 14 60 57 13]
 [32 54  4 51 11 49 36 26 24 59]
 [34 88 47  9 17 51 17 50 62 30]
 [46 36 90  7  3 11 49 42 57 92]
 [32 26 70 20  2 92 56 38 19 80]
 [40 40 63 24 10  7  3  8 64 62]]
maximum: 92 minimum: 0


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
vector = rng.random(30)
mean = np.mean(vector)
mean

0.49270886538499303

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [18]:
mat2d = np.ones((6, 6), dtype=np.int32)
mat2d[1:-1, 1: -1] = 0
mat2d

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int32)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [19]:
matrix3d = rng.integers(10, 100, size=(3,3))
bordered = np.pad(matrix3d, pad_width = 1, constant_values = 0)
bordered

array([[ 0,  0,  0,  0,  0],
       [ 0, 11, 38, 57,  0],
       [ 0, 55, 98, 85,  0],
       [ 0, 15, 30, 53,  0],
       [ 0,  0,  0,  0,  0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [20]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [21]:
mat5x5 = np.diag(np.arange(1,5), k = -1)
mat5x5

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [22]:
board = np.zeros((8,8), dtype = np.int32)
board[1::2, ::2] = 1
board[::2, 1::2] = 1
board

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [23]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [24]:
def f(i, j):
    return (i + j) % 2
board = np.fromfunction(f, (8,8), dtype = np.int8)
board

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int8)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [25]:
mat = rng.integers(100, size=(5,5))
dfmax, dfmin = mat.max(), mat.min()
df = (mat - dfmin)/(dfmax - dfmin)
print(df)

[[0.17391304 1.         0.7173913  0.97826087 0.20652174]
 [0.76086957 0.2173913  0.47826087 0.31521739 0.97826087]
 [0.07608696 0.64130435 0.04347826 0.75       0.56521739]
 [0.61956522 0.36956522 0.23913043 0.0326087  0.34782609]
 [0.7173913  0.35869565 0.         0.7826087  0.27173913]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [26]:
rgbadt = np.dtype([('r', np.uint8), ('g', np.uint8), ('b', np.uint8), ('a', np.uint8)])
image = np.array([(13, 45, 56, 255), (53, 65, 136, 255), (183, 25, 96, 255)], dtype = rgbadt)
image

array([( 13, 45,  56, 255), ( 53, 65, 136, 255), (183, 25,  96, 255)],
      dtype=[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [27]:
mat5x3 = rng.integers(10, size=(5,3))
print(mat5x3)
mat3x2 = rng.integers(10, size=(3,2))
print(mat3x2)
product = np.matmul(mat5x3, mat3x2)
product

[[8 8 8]
 [0 8 5]
 [4 9 6]
 [4 0 3]
 [4 5 9]]
[[3 2]
 [5 6]
 [2 7]]


array([[ 80, 120],
       [ 50,  83],
       [ 69, 104],
       [ 18,  29],
       [ 55, 101]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [28]:
arr = np.arange(15)
arr[(arr > 3) & (arr < 8)] = -arr[(arr > 3) & (arr < 8)]
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [29]:
#print(sum(range(5),-1)) #9
#from numpy import *
#print(sum(range(5),-1))  #10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [30]:
Z = np.arange(3)
print(Z**Z)
print(2 << Z >> 2)
print(Z < -Z)
print(1j*Z)
print(Z/1/1)
#print(ZZ)

[1 1 4]
[0 1 2]
[False False False]
[0.+0.j 0.+1.j 0.+2.j]
[0. 1. 2.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [31]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/var/folders/0k/z_ctsmn523qdxr2rn5yd_lc80000gn/T/ipykernel_37764/548293649.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
/var/folders/0k/z_ctsmn523qdxr2rn5yd_lc80000gn/T/ipykernel_37764/548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [32]:
def roundAwayFromZero(array):
    a = np.abs(array)
    b = np.floor(a) + np.floor(2*(a%1))
    return np.copysign(b, array)

x = np.linspace(-5, 5, 20)
roundAwayFromZero(x)

array([-5., -4., -4., -3., -3., -2., -2., -1., -1., -0.,  0.,  1.,  1.,
        2.,  2.,  3.,  3.,  4.,  4.,  5.])

#### 30. How to find common values between two arrays? (★☆☆)

In [33]:
np.intersect1d([1,2,3,4], [3,5,6,7])

array([3])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [35]:
settings = np.seterr(all='ignore')
np.ones(1) / 0


array([inf])

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [36]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [37]:
today = np.datetime64('today', 'D')
tomorrow = today + np.timedelta64(1, 'D')
yesterday = today - np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2022-11-21 2022-11-22 2022-11-23


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [38]:
dates = np.arange(np.datetime64('2016-07'), np.datetime64('2016-08'), dtype = 'datetime64[D]')
dates

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [39]:
A = np.ones(3)
B = np.ones(3) * 2
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [40]:
x = rng.random(5, dtype=np.double)*10
print(x)
print(x.astype(np.int32))
print(np.trunc(x))
print(np.floor(x))
print(np.fix(x))

[0.35574109 1.79495278 6.05035028 2.3402235  0.81106858]
[0 1 6 2 0]
[0. 1. 6. 2. 0.]
[0. 1. 6. 2. 0.]
[0. 1. 6. 2. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [41]:
x = np.zeros((5,5))
x += np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [42]:
def generate_integers():
    for i in np.arange(10):
        yield i
np.fromiter(generate_integers(), dtype=np.int32)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [43]:
x = np.linspace(0, 1, num=12, endpoint=True)[1:-1]
x

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [44]:
x = rng.random(10)
x.sort()
x

array([0.02793109, 0.22706732, 0.29086676, 0.36176948, 0.52421365,
       0.72194774, 0.76541416, 0.79848073, 0.88140685, 0.88223939])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [45]:
x = np.arange(10)
np.add.reduce(x)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [47]:
A = np.random.randint(0, 2, size=5)
B = np.random.randint(0, 2, size=5)
print(A, B)

equal = np.allclose(A, B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

[0 0 0 0 0] [1 1 1 0 1]
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [48]:
Z = np.zeros(10)
Z.flags.writeable = False
print(Z.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [49]:
Z = np.random.random((10,2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.50479369 0.86721699 1.21486699 1.01565418 0.27258348 0.85292678
 0.91927932 0.42817159 0.93652598 0.71959961]
[0.7400038  1.35927237 0.731443   0.33203577 1.21866643 1.17030215
 1.24206565 0.50799508 1.4825195  0.07338074]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [50]:
Z = np.random.random(10)
print(Z)
Z[Z.argmax()] = 0
print(Z)

[0.72691003 0.3024807  0.30842066 0.25334006 0.2432482  0.92215313
 0.5606351  0.41635865 0.16523239 0.89673745]
[0.72691003 0.3024807  0.30842066 0.25334006 0.2432482  0.
 0.5606351  0.41635865 0.16523239 0.89673745]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [51]:
Z = np.zeros((5,5), [('x', np.float),('y', np.float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


/var/folders/0k/z_ctsmn523qdxr2rn5yd_lc80000gn/T/ipykernel_37764/296654516.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.zeros((5,5), [('x', np.float),('y', np.float)])


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [52]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(C)
print(np.linalg.det(C))

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]
3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [53]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [54]:
np.set_printoptions(threshold=256)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [55]:
Z = np.arange(100)
print(Z)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(Z-v)).argmin()
Z[index]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
43.34500351365561


43

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [56]:
Z = np.zeros(10, [ ('position', [ ('x', float),
                                  ('y', float)]),
                   ('color',    [ ('r', float),
                                  ('g', float),
                                  ('b', float)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [57]:
Z = np.random.random((5,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.82604808 0.12340474 0.48358632 0.25307129]
 [0.82604808 0.         0.87895117 0.91036546 0.65434742]
 [0.12340474 0.87895117 0.         0.37889864 0.36664518]
 [0.48358632 0.91036546 0.37889864 0.         0.65977834]
 [0.25307129 0.65434742 0.36664518 0.65977834 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [58]:
Z = np.arange(10, dtype=np.float32)
print(Z)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [59]:
from io import StringIO


s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int, filling_values=-1)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/var/folders/0k/z_ctsmn523qdxr2rn5yd_lc80000gn/T/ipykernel_37764/2003448768.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int, filling_values=-1)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [60]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
print()
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [61]:
X, Y = np.meshgrid(np.linspace(-1,1,6), np.linspace(-1,1,6))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.50661699 0.59452055 0.59452055 0.50661699 0.36787944]
 [0.50661699 0.69767633 0.81873075 0.81873075 0.69767633 0.50661699]
 [0.59452055 0.81873075 0.96078944 0.96078944 0.81873075 0.59452055]
 [0.59452055 0.81873075 0.96078944 0.96078944 0.81873075 0.59452055]
 [0.50661699 0.69767633 0.81873075 0.81873075 0.69767633 0.50661699]
 [0.36787944 0.50661699 0.59452055 0.59452055 0.50661699 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [62]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [63]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y

array([[-0.50468365, -0.39156289, -0.29078157,  0.42437172,  0.37680487,
        -0.32335277,  0.41991102,  0.07275279, -0.11617979,  0.33272028],
       [-0.15083579, -0.11247436, -0.36114098, -0.38744731,  0.39544406,
        -0.28811254,  0.36990162,  0.13963315,  0.21570957,  0.17932258],
       [ 0.04758068,  0.54561897,  0.06467151, -0.35973977, -0.24153799,
        -0.12952804,  0.19067569, -0.05523345, -0.14814023,  0.08563263],
       [-0.34712281,  0.54711044,  0.11339427,  0.29607109, -0.11480571,
        -0.20748584, -0.29473071,  0.3742228 , -0.16133446, -0.20531908],
       [-0.39556034, -0.18199191,  0.46307775, -0.41525956,  0.36156951,
         0.29521058, -0.26902592, -0.28819942,  0.52936321, -0.09918391]])

#### 59. How to sort an array by the nth column? (★★☆)

In [64]:
Z = np.random.randint(0,10,(4,4))
print(Z)
print(Z[Z[:,2].argsort()])

[[9 9 0 2]
 [0 7 3 4]
 [8 5 8 1]
 [7 7 9 1]]
[[9 9 0 2]
 [0 7 3 4]
 [8 5 8 1]
 [7 7 9 1]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [65]:
Z = np.random.randint(0,3,(3,10))
print(not (Z.any(axis=0).any()))

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [66]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = np.abs(Z - z).argmin()
print(Z[m])

0.48460136360588857


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [67]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [68]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [69]:

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
np.add.at(Z, I, 1)
print(Z)


[3. 2. 5. 3. 3. 4. 3. 3. 2. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [70]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [71]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [72]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[60 37 78 54]
 [63 62 56 61]
 [42 53 39 58]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [73]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.4845984  0.52438671 0.54115491 0.43322741 0.4164515  0.62633052
 0.50597754 0.53843068 0.47886658 0.59695572]


#### 69. How to get the diagonal of a dot product? (★★★)

In [74]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

array([1.4928306 , 1.92208319, 0.86533129, 1.38140562, 1.05323966])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [75]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [76]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [77]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [78]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 25) ( 0, 45) ( 3, 27) ( 3, 46) (13, 20) (13, 31) (13, 57) (13, 89)
 (20, 31) (23, 36) (23, 98) (25, 45) (26, 40) (26, 54) (27, 46) (31, 50)
 (31, 73) (35, 62) (35, 97) (36, 98) (37, 69) (37, 86) (40, 54) (50, 58)
 (50, 73) (50, 96) (57, 89) (58, 96) (62, 97) (69, 86)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [79]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [80]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [81]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [83]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 9.48275463e-01,  7.00013981e-01,  6.46492255e-01,  4.04392012e-01,
       -8.18547053e-01, -2.45724839e-01,  5.57052879e-01, -5.92715311e-01,
       -2.18126446e-01, -3.29701394e-01, -2.34546289e-01,  1.13718223e-01,
       -7.66966394e-01, -4.78300527e-01, -6.74186939e-01,  7.73073805e-01,
       -8.64191799e-01,  9.87018326e-02,  6.03316818e-01,  6.09821777e-01,
        5.42176441e-01, -2.02899985e-01, -8.56943589e-01,  4.24970880e-01,
        8.22760734e-01,  8.42926331e-01,  3.20799168e-01, -4.24010792e-01,
        3.60597827e-01,  3.18359802e-01, -2.46230673e-01, -8.80482684e-01,
       -8.39103082e-01, -1.81388155e-04, -8.42087166e-01, -1.60916942e-01,
       -3.54337502e-01,  9.03079732e-01, -3.07322431e-01, -8.00047999e-01,
        7.73048752e-01, -6.97624903e-01, -1.72603300e-02,  3.81923035e-01,
        8.21515113e-02,  6.19998527e-01, -2.46746147e-01,  1.02389307e-01,
        6.14594690e-01, -9.95781481e-01, -1.17582132e-01, -7.53416466e-02,
        9.15656420e-01,  

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [84]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[13.10575279  2.44632152 10.02026279  0.0491446   4.20802902  8.73579418
  6.15865044 12.74116854  4.57447158  1.37905651]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [85]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 1.418018    1.61124202  8.27600984  2.61328323  2.76650186  1.30467705
   9.04172441  7.28082489 12.0268484   0.18635443]
 [17.59072053  2.27876673 12.97234458  6.80955858  4.58298921  0.86630812
   0.83123065  7.48231727  8.81314459 14.76107917]
 [ 7.30954774  5.34579597  4.59135709  3.72152969  2.19814784  6.81585983
   0.87202757  4.10886571  5.26800122  7.54512747]
 [ 7.8476648   6.30339507  3.94105098  4.08681688  2.97879303  7.64901175
   0.14010748  3.94743614  4.32570262  8.38425493]
 [ 7.52579936  6.34510266  3.73156666  4.37199071  3.13592836  7.77967697
   0.04195344  4.28868629  4.26949936  8.13593692]
 [ 9.81841234  4.61969408  6.61478074  1.16998272  0.56605863  5.38687772
   0.43795661  1.28921793  6.11058078  9.31521667]
 [14.34804152  3.02062917 16.43228648  8.62465147  8.80871699  3.6720398
   4.87901098  6.32196035 14.01624337  9.89892747]
 [ 8.77434728  3.6725636   6.98944921  1.20780994  0.02353377  4.70272708
   1.64985986  1.96512817  7.0201038   8.06301584]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [86]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)


[[5 7 8 7 1 7 1 5 4 6]
 [4 0 6 6 4 8 8 1 1 0]
 [6 0 1 9 8 3 3 8 4 9]
 [4 8 6 4 3 6 9 5 4 6]
 [5 8 6 8 1 4 8 2 7 8]
 [0 8 5 6 5 6 7 9 2 5]
 [1 8 7 7 7 1 1 6 7 2]
 [7 5 0 2 3 5 5 5 8 9]
 [2 6 9 7 0 1 4 4 8 3]
 [6 4 7 5 8 2 5 6 3 7]]
[[0 0 0 0 0]
 [0 5 7 8 7]
 [0 4 0 6 6]
 [0 6 0 1 9]
 [0 4 8 6 4]]


/var/folders/0k/z_ctsmn523qdxr2rn5yd_lc80000gn/T/ipykernel_37764/1540182574.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [87]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [88]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [89]:

Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

9


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [90]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 0 3]
   [3 2 2]
   [0 4 1]]

  [[0 3 4]
   [2 2 4]
   [4 1 3]]

  [[3 4 3]
   [2 4 1]
   [1 3 1]]

  ...

  [[3 4 2]
   [2 0 0]
   [4 3 1]]

  [[4 2 3]
   [0 0 0]
   [3 1 2]]

  [[2 3 2]
   [0 0 0]
   [1 2 1]]]


 [[[3 2 2]
   [0 4 1]
   [3 2 2]]

  [[2 2 4]
   [4 1 3]
   [2 2 0]]

  [[2 4 1]
   [1 3 1]
   [2 0 4]]

  ...

  [[2 0 0]
   [4 3 1]
   [1 1 2]]

  [[0 0 0]
   [3 1 2]
   [1 2 3]]

  [[0 0 0]
   [1 2 1]
   [2 3 2]]]


 [[[0 4 1]
   [3 2 2]
   [4 4 4]]

  [[4 1 3]
   [2 2 0]
   [4 4 3]]

  [[1 3 1]
   [2 0 4]
   [4 3 1]]

  ...

  [[4 3 1]
   [1 1 2]
   [0 0 1]]

  [[3 1 2]
   [1 2 3]
   [0 1 3]]

  [[1 2 1]
   [2 3 2]
   [1 3 0]]]


 ...


 [[[0 2 4]
   [1 2 0]
   [3 0 4]]

  [[2 4 0]
   [2 0 2]
   [0 4 2]]

  [[4 0 2]
   [0 2 4]
   [4 2 0]]

  ...

  [[4 2 3]
   [0 1 2]
   [3 3 2]]

  [[2 3 0]
   [1 2 1]
   [3 2 2]]

  [[3 0 2]
   [2 1 0]
   [2 2 4]]]


 [[[1 2 0]
   [3 0 4]
   [0 4 2]]

  [[2 0 2]
   [0 4 2]
   [4 2 1]]

  [[0 2 4]
   [4 2 0]
   [2 1 3]]

  ...

  [[0

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [92]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 3 10 14  6  6]
 [10  8  6  5  8]
 [14  6  3 42  7]
 [ 6  5 42  1  9]
 [ 6  8  7  9  2]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [93]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [94]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [95]:
def iterate(Z):

    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [97]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

print (Z[np.argpartition(-Z,n)[:n]])


[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [98]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [99]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [100]:
x = np.random.randint(5e4)

%timeit np.power(x,3)
%timeit x*x*x

1.92 µs ± 199 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
160 ns ± 17.8 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [102]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 2 3 5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [103]:
Z = np.random.randint(0,5,(10,3))
print(Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[2 2 4]
 [1 3 4]
 [0 0 4]
 [4 2 1]
 [4 3 1]
 [2 3 4]
 [4 2 4]
 [4 1 4]
 [2 2 1]
 [4 4 2]]
[[2 2 4]
 [1 3 4]
 [0 0 4]
 [4 2 1]
 [4 3 1]
 [2 3 4]
 [4 2 4]
 [4 1 4]
 [2 2 1]
 [4 4 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [104]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [105]:
Z = np.random.randint(0,2,(6,3))
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [106]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)      
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B) 

array([[0.5629651 , 0.0618347 , 0.1413479 , 0.31769292, 0.37612245,
        0.47840544, 0.39969834, 0.19539126, 0.45844852, 0.3384743 ],
       [0.23463222, 0.02577142, 0.05891088, 0.13240785, 0.15676007,
        0.1993895 , 0.16658601, 0.08143504, 0.19107187, 0.14106909],
       [0.05318918, 0.00584217, 0.01335461, 0.03001576, 0.03553621,
        0.04519995, 0.03776367, 0.01846065, 0.04331441, 0.0319792 ],
       [0.94910763, 0.10424764, 0.23829962, 0.53560119, 0.63410803,
        0.80654778, 0.67385482, 0.32941178, 0.77290225, 0.57063669],
       [0.50193053, 0.05513081, 0.12602349, 0.28324985, 0.33534467,
        0.42653851, 0.35636454, 0.17420767, 0.40874525, 0.30177818],
       [0.15550033, 0.01707977, 0.03904264, 0.08775207, 0.10389128,
        0.13214354, 0.11040333, 0.05397032, 0.12663111, 0.09349223],
       [0.64127047, 0.07043557, 0.16100862, 0.36188227, 0.42843903,
        0.54494902, 0.45529419, 0.22256912, 0.52221621, 0.38555422],
       [0.24443173, 0.02684778, 0.0613713

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [107]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)      
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [108]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [109]:
X = np.random.randn(100)
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.1723562   0.23719505]
