# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
np.version.version

'1.23.1'

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [17]:
x = np.array([10,20,100])
a=x.size * x.itemsize 
a

12

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [18]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [19]:
(np.arange(10) == 4).astype(int)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [21]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [22]:
x = np.array([10,20,100])
np.flip(x)

array([100,  20,  10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [24]:
x =  np.arange(0, 9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [25]:
x= np.nonzero([1,2,0,0,4,0])
x

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [26]:
x = np.identity(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [27]:
x = np.random.random((3,3,3))
x

array([[[0.43345112, 0.73190181, 0.87213104],
        [0.53742084, 0.34623233, 0.76329205],
        [0.17495985, 0.76173496, 0.40398741]],

       [[0.81920744, 0.15098886, 0.59325274],
        [0.77482763, 0.48681598, 0.44318489],
        [0.28363932, 0.66851525, 0.97850196]],

       [[0.86713202, 0.84403411, 0.21485129],
        [0.03342844, 0.98694337, 0.86253196],
        [0.22662953, 0.42276159, 0.36533074]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [29]:
x = np.random.random((10,10))
x.min(), x.max()

(0.004924854839492565, 0.9988775349245156)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [30]:
x = np.random.random(30)
x.min()

0.00030143667882043257

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [32]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [34]:
x = np.zeros((3,3))
x = np.pad(x, pad_width=1, mode='constant', constant_values=1)
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [35]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [36]:
x = np.diag(1+np.arange(4), k = -1)
x

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [41]:
x = np.zeros ((8,8), dtype=int)
x[1::2, ::2]= 1
x[::2, 1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [42]:
x = np.unravel_index(100, (6,7,8))
x

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [43]:
y= np.array([[0,1], [1,0]])
x = np.tile(y,(4,4))
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [44]:
x = np.random.random((5,5))
x= (x-x.min())/(x.max()-x.min())
x

array([[0.76217166, 0.43096256, 0.08445316, 0.45042568, 0.0811167 ],
       [0.68037535, 0.99840064, 0.553894  , 0.59120377, 0.36064101],
       [0.61296837, 0.        , 0.15984931, 1.        , 0.12251705],
       [0.21737634, 0.32962296, 0.58531747, 0.30243642, 0.51646243],
       [0.37762901, 0.17472098, 0.48643551, 0.97896048, 0.9382564 ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [47]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

C:\Users\t-1000\AppData\Local\Temp\ipykernel_17076\2911720781.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [48]:
x = np.dot(np.ones((5,3)), np.ones((3,2)))
x = np.ones((5,3)) @ np.ones((3,2))
x

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [50]:
x = np.arange(11)
x[(3 < x) & (x < 8)] *= -1
x

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [51]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [54]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [55]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

C:\Users\t-1000\AppData\Local\Temp\ipykernel_17076\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\t-1000\AppData\Local\Temp\ipykernel_17076\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


nan
0
[-2.14748365e+09]


#### 29. How to round away from zero a float array ? (★☆☆)

In [57]:
x = np.random.uniform(-10,+10,10)
x= np.copysign(np.ceil(np.abs(x)), x)
x

array([-5., -6.,  9., -7.,  4.,  1.,  1., -6.,  8., -1.])

#### 30. How to find common values between two arrays? (★☆☆)

In [59]:
x1 = np.random.randint(0,10,10)
x2 = np.random.randint(0,10,10)
x = np.intersect1d(x1,x2)
x

array([2, 5, 8])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [60]:
defaults = np.seterr(all="ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [61]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [64]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2022-10-14 2022-10-15 2022-10-16


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [65]:
x= np.arange('2016-07', '2016-08', dtype='datetime64[D]')
x

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [67]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [70]:
x = np.random.uniform(0,10,10)

print (x - x%1)
print (np.floor(x))
print (np.trunc(x))
print (np.trunc(x))

[1. 7. 1. 7. 2. 8. 7. 7. 7. 3.]
[1. 7. 1. 7. 2. 8. 7. 7. 7. 3.]
[1. 7. 1. 7. 2. 8. 7. 7. 7. 3.]
[1. 7. 1. 7. 2. 8. 7. 7. 7. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [72]:
x = np.zeros((5,5))
x += np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [73]:
def generator():
    for x in range(10):
        yield x
y = np.fromiter(generator(),dtype=float,count=-1)
y

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [74]:
x = np.linspace(0,1,11,endpoint=False)[1:]
x

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [88]:
x = np.random.randint(10, size = 10)
print(x)
x.sort()
x

[7 9 0 2 6 0 7 3 7 2]


array([0, 0, 2, 2, 3, 6, 7, 7, 7, 9])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [89]:
x = np.arange(10)
np.add.reduce(x)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [93]:
A = np.random.randint(0,2,2)
B = np.random.randint(0,2,2)
equals = np.array_equal(A, B)
equals

False

#### 43. Make an array immutable (read-only) (★★☆)

In [95]:
x = np.zeros(10)
x.flags.writeable = False
x[0]=1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [98]:
x = np.random.random((10,2))
X,Y = x[:,0], x[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.99255704 1.07382374 0.65994175 0.198545   0.77213887 0.86994816
 1.19423844 0.12184952 0.74668954 1.02227706]
[0.52287617 0.82272218 1.52362812 1.41208112 0.0850191  0.89301063
 0.74632981 1.26979596 0.12365714 0.22275444]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [109]:
x = np.random.random(10)
print(x)
x[x.argmax()] = 0
print(x)

[0.06788904 0.86482193 0.12262707 0.83534306 0.84013644 0.92149477
 0.64116489 0.41425218 0.84392386 0.8534239 ]
[0.06788904 0.86482193 0.12262707 0.83534306 0.84013644 0.
 0.64116489 0.41425218 0.84392386 0.8534239 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [108]:
x = np.zeros((5,5), [('x',float),('y',float)])
x['x'], x['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(x)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [115]:
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x, y)
print(np.linalg.det(c))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [116]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [121]:
x = np.zeros((3,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [122]:
x = np.arange(100)
y = np.random.uniform(0,100)
index = (np.abs(x-y)).argmin()
print(x[index])

15


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [123]:
x = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(x)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\t-1000\AppData\Local\Temp\ipykernel_17076\2893404235.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  x = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [125]:
W = np.random.random((100,2))
X,Y = np.atleast_2d(W[:,0], W[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.89142763 0.13584835 ... 0.58466865 0.24073778 0.88034694]
 [0.89142763 0.         0.87086414 ... 0.49026353 1.02949202 0.15248678]
 [0.13584835 0.87086414 0.         ... 0.50040432 0.37328104 0.88323403]
 ...
 [0.58466865 0.49026353 0.50040432 ... 0.         0.8016073  0.57866159]
 [0.24073778 1.02949202 0.37328104 ... 0.8016073  0.         0.98546555]
 [0.88034694 0.15248678 0.88323403 ... 0.57866159 0.98546555 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [126]:
x = np.arange(10, dtype=np.float32)
x = x.astype(np.int32, copy=False)
print(x)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [127]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
x = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(x)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\t-1000\AppData\Local\Temp\ipykernel_17076\2144851346.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.genfromtxt(s, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [128]:
x = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(x):
    print(index, value)
for index in np.ndindex(x.shape):
    print(index, x[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [129]:
X, Y = np.meshgrid(np.linspace(-1,1,5), np.linspace(-1,1,5))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.60653066 0.8824969  1.         0.8824969  0.60653066]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [130]:
n = 4
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),3)
print(Z)

[[0. 0. 3. 3.]
 [3. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [131]:
x = np.random.rand(5, 10)
t = x - x.mean(axis=1, keepdims=True)
t = x - x.mean(axis=1).reshape(-1, 1)
print(t)

[[ 0.41899957  0.34455103 -0.38623807 -0.3380726   0.10568894 -0.52827604
   0.41186177  0.38743445  0.12258315 -0.53853219]
 [ 0.25114501  0.39271531  0.07459254  0.26635626 -0.17020729 -0.32774232
  -0.15765217  0.04036815 -0.13865869 -0.2309168 ]
 [-0.23090853  0.08398195 -0.194721   -0.021741   -0.31307132  0.28799161
  -0.10359017  0.39167067  0.40595283 -0.30556503]
 [ 0.04450323  0.5303503   0.38672867 -0.0637109  -0.18363175 -0.21382288
   0.03624889  0.13626646 -0.24166717 -0.43126484]
 [ 0.16115942  0.08093908 -0.26718366 -0.13752322  0.47704954 -0.17432656
   0.415927   -0.49047593  0.15800471 -0.22357037]]


#### 59. How to sort an array by the nth column? (★★☆)

In [133]:
x = np.random.randint(0,10,(3,3))
print(x)
print(x[x[:,1].argsort()])

[[1 5 4]
 [2 8 2]
 [5 6 9]]
[[1 5 4]
 [5 6 9]
 [2 8 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [134]:
x= np.random.randint(0,3,(3,10))
print((~x.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [136]:
X = np.random.uniform(0,1,10)
t = 0.5
m = X.flat[np.abs(X - t).argmin()]
print(m)

0.4723160836848903


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [137]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,t in it: t[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [139]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

x = NamedArray(np.arange(5), "range_5")
print (x.name)

range_5


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [140]:
X = np.ones(10)
I = np.random.randint(0,len(X),20)
np.add.at(X, I, 1)
print(X)

[3. 4. 3. 2. 4. 2. 3. 7. 1. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [141]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
F

array([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [144]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [145]:
A = np.random.randint(0,10,(3,3,3,3))
sum = A.sum(axis=(-2,-1))
print(sum)


[[31 52 34]
 [39 36 45]
 [46 40 64]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [147]:
import pandas as pd
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
print(pd.Series(D).groupby(S).mean())

0    0.537342
1    0.468900
2    0.448653
3    0.508423
4    0.491203
5    0.493802
6    0.584880
7    0.484949
8    0.346870
9    0.461467
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [148]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5)) 
np.diag(np.dot(A, B))

array([0.98917072, 1.09499698, 1.81477018, 0.74100354, 0.82096902])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [149]:
x = np.array([1,2,3,4,5])
nx = 3
x0 = np.zeros(len(x) + (len(x)-1)*(nx))
x0[::nx+1] = x
print(x0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [150]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [153]:
A = np.arange(9).reshape(3,3)
A[[0,1]] = A[[1,0]]
print(A)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [154]:
f = np.random.randint(0,100,(10,3))
F = np.roll(f.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 8, 24) ( 8, 64) (10, 56) (10, 88) (11, 55) (11, 82) (22, 54) (22, 64)
 (24, 64) (26, 48) (26, 62) (30, 75) (30, 81) (30, 89) (30, 96) (36, 69)
 (36, 83) (41, 66) (48, 62) (51, 69) (51, 93) (54, 64) (55, 82) (56, 88)
 (66, 66) (69, 83) (69, 93) (75, 81) (89, 96)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [155]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [156]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
x = np.arange(20)
print(moving_average(x, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [158]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [161]:
x = np.random.randint(0,2,100)
np.logical_not(x, out=x)

x = np.random.uniform(-1.0,1.0,100)
np.negative(x, out=x)

array([-0.25509213,  0.63278578, -0.17248434, -0.57956147, -0.62058897,
        0.50806742,  0.4879593 , -0.31019277, -0.59088608,  0.44618065,
        0.8381961 ,  0.13097933, -0.56358861,  0.04163488, -0.40574457,
        0.61650449, -0.35308895, -0.66136899, -0.19723805,  0.58830169,
        0.03458989, -0.153217  ,  0.35765889, -0.34444014, -0.75104879,
       -0.12935052,  0.67910673,  0.43370844,  0.52452533, -0.64872276,
        0.074543  ,  0.36491179,  0.24515451, -0.12786899,  0.65760327,
       -0.58230887, -0.86015333, -0.94971716, -0.02664097,  0.45917035,
       -0.43046263,  0.92283843,  0.02594853,  0.26602099,  0.71020361,
        0.74920754, -0.83853121,  0.55006466, -0.88571893, -0.26460973,
       -0.67849442,  0.87940173, -0.80181112,  0.7811404 , -0.86322913,
        0.69121765, -0.38417204, -0.82575647, -0.73300219,  0.52275102,
       -0.96625365,  0.11005659,  0.9935434 ,  0.19567713, -0.16608383,
       -0.86442912, -0.40427576, -0.95527077, -0.85650319,  0.04

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [162]:
def dist(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(dist(P0, P1, p))

[12.69461303  5.94523724 12.86754029 12.76850169 10.60525925 14.72946866
  5.8242943   0.80964161 12.82567814 11.62023888]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [164]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,pi) for pi in p]))

[[ 2.18547674  0.7629596   5.80162302  4.64496258  0.30123476  8.77115912
   3.53749085  7.24602656  5.84557244  1.20171502]
 [11.99411597 12.20346365  5.71942974  5.88080406  5.29183757  3.40189828
   8.31268497  4.40619991  7.36801627  4.27202707]
 [ 5.03623036  4.29184691  2.23795463  1.50151286  2.34183024  4.2001821
   0.17010243  2.80395574  1.48637637  1.40302714]
 [ 9.82081822  7.00209772  0.35148325  2.44629144  9.25693462 12.80787123
   2.2404268  11.98204207  2.34635764 10.2026785 ]
 [ 1.06230655  0.66693266  7.2474244   5.89979956  1.53995579 10.77247093
   5.04936067  9.20090863  7.66369974  2.42463091]
 [10.68606017  9.67337285  3.12257239  4.06189254  0.46745807  3.31138071
   5.4341059   2.34831813  3.04949818  1.45341502]
 [ 9.03250156  9.4889457   3.02185711  3.00850018  7.29580069  3.47544714
   5.69091603  4.7185433   5.26127078  6.29880665]
 [ 2.78491133  2.10497549  4.41882712  3.73594874  3.24930411  4.76954054
   1.98236286  3.20538903  3.40189118  2.33004914]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [173]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [174]:
Z = np.random.uniform(0,1,(5,5))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print(rank)

5


#### 83. How to find the most frequent value in an array?

In [175]:
X = np.random.randint(0,10,50)
print(np.bincount(X).argmax())

3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [176]:
x = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (x.shape[0]-3)
j = 1 + (x.shape[1]-3)
C = stride_tricks.as_strided(x, shape=(i, j, n, n), strides=x.strides + x.strides)
print(C)

[[[[1 0 4]
   [0 1 1]
   [2 1 3]]

  [[0 4 1]
   [1 1 0]
   [1 3 3]]

  [[4 1 2]
   [1 0 2]
   [3 3 3]]

  [[1 2 4]
   [0 2 3]
   [3 3 2]]

  [[2 4 4]
   [2 3 2]
   [3 2 3]]

  [[4 4 4]
   [3 2 0]
   [2 3 4]]

  [[4 4 3]
   [2 0 4]
   [3 4 4]]

  [[4 3 1]
   [0 4 3]
   [4 4 4]]]


 [[[0 1 1]
   [2 1 3]
   [3 3 1]]

  [[1 1 0]
   [1 3 3]
   [3 1 1]]

  [[1 0 2]
   [3 3 3]
   [1 1 4]]

  [[0 2 3]
   [3 3 2]
   [1 4 4]]

  [[2 3 2]
   [3 2 3]
   [4 4 4]]

  [[3 2 0]
   [2 3 4]
   [4 4 3]]

  [[2 0 4]
   [3 4 4]
   [4 3 1]]

  [[0 4 3]
   [4 4 4]
   [3 1 2]]]


 [[[2 1 3]
   [3 3 1]
   [0 1 0]]

  [[1 3 3]
   [3 1 1]
   [1 0 0]]

  [[3 3 3]
   [1 1 4]
   [0 0 4]]

  [[3 3 2]
   [1 4 4]
   [0 4 4]]

  [[3 2 3]
   [4 4 4]
   [4 4 4]]

  [[2 3 4]
   [4 4 3]
   [4 4 3]]

  [[3 4 4]
   [4 3 1]
   [4 3 1]]

  [[4 4 4]
   [3 1 2]
   [3 1 3]]]


 [[[3 3 1]
   [0 1 0]
   [4 2 1]]

  [[3 1 1]
   [1 0 0]
   [2 1 1]]

  [[1 1 4]
   [0 0 4]
   [1 1 2]]

  [[1 4 4]
   [0 4 4]
   [1 2 1]]

  [[4 4 4]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [177]:
class Sym(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Sym, self).__setitem__((i,j), value)
        super(Sym, self).__setitem__((j,i), value)

def symetric(x):
    return np.asarray(x + x.T - np.diag(x.diagonal())).view(Sym)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 3  8  7  5  6]
 [ 8  2 11 16  4]
 [ 7 11  9 42 10]
 [ 5 16 42  8  5]
 [ 6  4 10  5  9]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [178]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [179]:
X = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(X, np.arange(0, X.shape[0], k), axis=0),
                                       np.arange(0, X.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [181]:
def iterate(G):
    N = (G[0:-2,0:-2] + G[0:-2,1:-1] + G[0:-2,2:] +
         G[1:-1,0:-2]                + G[1:-1,2:] +
         G[2:  ,0:-2] + G[2:  ,1:-1] + G[2:  ,2:])
    
    birth = (N==3) & (G[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (G[1:-1,1:-1]==1)
    G[...] = 0
    G[1:-1,1:-1][birth | survive] = 1
    return G

G = np.random.randint(0,2,(50,50))
for i in range(100): G = iterate(G)
G

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

#### 89. How to get the n largest values of an array (★★★)

In [183]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [184]:
def cart(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cart(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [185]:
L = np.array([("A", 1.5, 3),
              ("B", 1.6, 2)])
R = np.core.records.fromarrays(L.T, names='col1, col2, col3', formats = 'S8, f8, i8')
print(R)

[(b'A', 1.5, 3) (b'B', 1.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [187]:
x = np.random.rand(100)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

4.68 µs ± 139 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
1.01 µs ± 23.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
33.1 µs ± 18.2 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [188]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 5]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [193]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[3 0 0]
 [3 2 0]
 [2 3 2]
 [4 4 3]
 [2 3 3]
 [0 1 1]
 [0 1 1]
 [3 4 0]
 [0 4 1]
 [0 4 0]]
[[3 0 0]
 [3 2 0]
 [2 3 2]
 [4 4 3]
 [2 3 3]
 [0 1 1]
 [0 1 1]
 [3 4 0]
 [0 4 1]
 [0 4 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [195]:
X = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(X[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [196]:
X = np.random.randint(0,2,(6,3))
uR = np.unique(X, axis=0)
print(uR)

[[0 0 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [198]:
A = np.random.uniform(0,1,3)
B = np.random.uniform(0,1,3)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B) 
np.einsum('i,j->ij', A, B)

array([[0.10380608, 0.34288402, 0.41374162],
       [0.03182283, 0.10511466, 0.12683679],
       [0.09683657, 0.3198629 , 0.38596315]])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [199]:
f = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*f*np.cos(f)
y = a*f*np.sin(f)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)     
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [212]:
X = np.asarray([[2.0, 1.0, 3.0, 3.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.3, 0.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [213]:
X = np.random.randn(100) 
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.02127056  0.37461014]
