# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [333]:
import numpy as nmp

#### 2. Print the numpy version and the configuration (★☆☆)

In [334]:
print(nmp.__version__)
print(nmp.show_config())

1.23.4
openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBO

#### 3. Create a null vector of sivectore 10 (★☆☆)

In [335]:
nullVector = nmp.zeros(10)
print(nullVector)

[0. 0. 0. ... 0. 0. 0.]


#### 4. How to find the memory sivectore of any array (★☆☆)

In [336]:
Memmory_vector_null=nullVector.size*nullVector.itemsize
print(Memmory_vector_null)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [337]:
!python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of sivectore 10 but the fifth value which is 1 (★☆☆)

In [338]:
vector = nmp.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. ... 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [339]:
vector = nmp.arange(10,50)
print(vector)

[10 11 12 ... 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [340]:
vector=vector[::-1]
print(vector)

[49 48 47 ... 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [341]:
vector=nmp.arange(9).reshape(3,3)
print(vector)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-vectorero elements from [1,2,0,0,4,0] (★☆☆)

In [342]:
NonZero = nmp.nonzero([0,1,1,1])
print(NonZero)

(array([1, 2, 3], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [343]:
matrix = nmp.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [344]:
vector = nmp.random.random((3,3,3))
print(vector)

[[[0.4000898  0.93727762 0.23584267]
  [0.9067271  0.33859548 0.82821155]
  [0.07975473 0.98901181 0.35068714]]

 [[0.25779471 0.33669723 0.89394317]
  [0.33426358 0.33165335 0.31454636]
  [0.93633144 0.02636105 0.05760491]]

 [[0.50477365 0.24892649 0.32023593]
  [0.00271868 0.82427629 0.24658414]
  [0.2208733  0.15887497 0.9470053 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [345]:
vectorMin, vectorMax = vector.min(), vector.max()
print(vectorMin, vectorMax)

0.0027186799136027506 0.9890118126538061


#### 14. Create a random vector of sivectore 30 and find the mean value (★☆☆)

In [346]:
vector = nmp.random.random(30);
print(vector.mean())

0.5283385629892553


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [347]:
vector=nmp.ones((3,3))
vector[1:-1,1:-1] = 0
print(vector)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [348]:
vector = nmp.ones((2,2))
vector = nmp.pad(vector, pad_width=1, mode='constant', constant_values=0)
print(vector)

[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [349]:
print(0 * nmp.nan)
print(nmp.nan == nmp.nan)
print(nmp.inf > nmp.nan)
print(nmp.nan - nmp.nan)
print(nmp.nan in set([nmp.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [350]:
print(nmp.diag(1+nmp.arange(4),k=-1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [351]:
checkerboard = nmp.zeros((8,8),dtype=int)
checkerboard[1::2,::2] = 1
checkerboard[::2,1::2] = 1
print(checkerboard)

[[0 1 0 ... 1 0 1]
 [1 0 1 ... 0 1 0]
 [0 1 0 ... 1 0 1]
 ...
 [1 0 1 ... 0 1 0]
 [0 1 0 ... 1 0 1]
 [1 0 1 ... 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,vector) of the 100th element? (★☆☆)

In [352]:
print(nmp.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [353]:
checkerboard = nmp.tile( nmp.array([[0,1],[1,0]]), (4,4))
print(checkerboard)

[[0 1 0 ... 1 0 1]
 [1 0 1 ... 0 1 0]
 [0 1 0 ... 1 0 1]
 ...
 [1 0 1 ... 0 1 0]
 [0 1 0 ... 1 0 1]
 [1 0 1 ... 0 1 0]]


#### 22. Normalivectore a 5x5 random matrix (★☆☆)

In [354]:
matrix = nmp.random.random((5,5))
matrix  = (matrix  - nmp.mean (matrix)) / (nmp.std (matrix))
print(vector)

[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [355]:
custom_dtype = nmp.dtype([
    ('r',nmp.ubyte,1),
    ('g', nmp.ubyte, 1),
    ('b', nmp.ubyte, 1),
    ('a', nmp.ubyte, 1)])
print(custom_dtype)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


C:\Users\romac\AppData\Local\Temp\ipykernel_21428\325070627.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  custom_dtype = nmp.dtype([


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [356]:
multiply_matrix = nmp.dot(nmp.ones((5,3)),nmp.ones((3,2)))
print(multiply_matrix)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [357]:
_1d_array = nmp.arange(11)
_1d_array[(3<_1d_array)&(_1d_array<=8)]*=-1
print(_1d_array)

[ 0  1  2 ... -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [358]:
9
10

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [359]:
Z = vector = nmp.zeros((5,5))

#### 28. What are the result of the following expressions? (★☆☆)
```python
nmp.array(0) / nmp.array(0)
nmp.array(0) // nmp.array(0)
nmp.array([nmp.nan]).astype(int).astype(float)
```

print(nmp.array(0) / nmp.array(0))
print(nmp.array(0) // nmp.array(0))
print(nmp.array([nmp.nan]).astype(int).astype(float))

#### 29. How to round away from zero a float array ? (★☆☆)

In [360]:
vector=nmp.zeros(10);
vector=nmp.random.uniform(-1,+1,10)
nmp.copysign(nmp.ceil(nmp.abs(vector)),vector)

array([ 1.,  1.,  1., ...,  1., -1., -1.])

In [361]:
#### 30. How to find common values between two arrays? (★☆☆)

In [362]:
arr1 = [1,2,3,4,5]
arr2=[5,7,5,3,2]
nmp.intersect1d(arr1,arr2)

array([2, 3, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [363]:
#nmp.seterr(all="ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
nmp.sqrt(-1) == nmp.emath.sqrt(-1)
```

In [364]:
False

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [365]:
yesterday = nmp.datetime64('today', 'D') - nmp.timedelta64(1, 'D')
today     = nmp.datetime64('today', 'D')
tomorrow  = nmp.datetime64('today', 'D') + nmp.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2022-12-04
2022-12-05
2022-12-06


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [366]:
july_days = nmp.arange('2016-07','2016-08',dtype='datetime64[D]')
july_days

array(['2016-07-01', '2016-07-02', '2016-07-03', ..., '2016-07-29',
       '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [367]:
A = 2
B= 4
nmp.multiply(nmp.add(A,B),(nmp.divide(nmp.negative(A),2)))

-6.0

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [368]:
vector=nmp.random.uniform(0,10,10)

print (vector - vector%1)
print (nmp.floor(vector))
print (nmp.ceil(vector)-1)
print (vector.astype(int))
print (nmp.trunc(vector))

[7. 8. 3. ... 4. 5. 8.]
[7. 8. 3. ... 4. 5. 8.]
[7. 8. 3. ... 4. 5. 8.]
[7 8 3 ... 4 5 8]
[7. 8. 3. ... 4. 5. 8.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [369]:
vector = nmp.zeros((5,5))
vector += nmp.arange(5)
print(vector)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [370]:
def generator():
    for x in range(10):
        yield x
vector = nmp.fromiter(generator(),dtype=float,count=-1)
print(vector)

[0. 1. 2. ... 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [371]:
vector = nmp.linspace(0,1,11,endpoint=False)[1:]
print(vector)

[0.09090909 0.18181818 0.27272727 ... 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [372]:
vector = nmp.random.random(10)
vector.sort()
vector

array([0.00309746, 0.00377643, 0.0062032 , ..., 0.70225428, 0.89837342,
       0.92281662])

#### 41. How to sum a small array faster than nmp.sum? (★★☆)

In [373]:
vector = nmp.arange(10)
nmp.add.reduce(vector)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [374]:
A = [1,2,3]
B  = [1,2,4]

equal = nmp.allclose(A,B)
print(equal)

equal = nmp.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [375]:
vector.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [376]:
vector = nmp.random.random((10,2))
X,Y = vector[:,0], vector[:,1]
R = nmp.sqrt(X**2+Y**2)
T = nmp.arctan2(Y,X)
print(R)
print(T)

[1.37746076 0.8467144  0.8659385  ... 0.70638438 0.37706065 1.13923467]
[0.7911396  0.20839746 0.85241475 ... 0.93460172 0.83209013 0.90501123]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [377]:
vector = nmp.array([1,2,3,4])
vector[vector.argmax()] = 0
print(vector)

[1 2 3 0]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [378]:
vector = nmp.zeros((5,5), [('x',float),('y',float)])
vector['x'], vector['y'] = nmp.meshgrid(nmp.linspace(0,1,5),
                             nmp.linspace(0,1,5))
print(vector)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [379]:
X = nmp.arange(8)
Y = X + 0.5
C = 1.0 / nmp.subtract.outer(X, Y)
print(nmp.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [380]:
for dtype in [nmp.int8, nmp.int32, nmp.int64]:
   print(nmp.iinfo(dtype).min)
   print(nmp.iinfo(dtype).max)
for dtype in [nmp.float32, nmp.float64]:
   print(nmp.finfo(dtype).min)
   print(nmp.finfo(dtype).max)
   print(nmp.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [381]:
nmp.set_printoptions(threshold=0)
matrix = nmp.zeros((4,4))
print(matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [382]:
vector = nmp.arange(100)

num = nmp.random.uniform(0,100);

index = (nmp.abs(vector-num)).argmin()
print(vector[index])


2


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [383]:


array = nmp.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(array)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ... ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\romac\AppData\Local\Temp\ipykernel_21428\1562268534.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  array = nmp.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [384]:
vector = nmp.random.random((100,2))
X,Y = nmp.atleast_2d(vector[:,0], vector[:,1])
distance = nmp.sqrt( (X-X.T)**2 + (Y-Y.T)**2)

print(distance)


[[0.         0.83566494 0.59712507 ... 0.71525499 0.45066003 0.72477342]
 [0.83566494 0.         0.89717174 ... 0.28228435 0.47433469 0.25618178]
 [0.59712507 0.89717174 0.         ... 0.62968945 0.81716169 0.95942798]
 ...
 [0.71525499 0.28228435 0.62968945 ... 0.         0.5095467  0.4459628 ]
 [0.45066003 0.47433469 0.81716169 ... 0.5095467  0.         0.28849708]
 [0.72477342 0.25618178 0.95942798 ... 0.4459628  0.28849708 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [385]:

array = nmp.arange(5, dtype=nmp.float32)
print(array)
array = array.astype(nmp.int32, copy=False)
print(array)

[0. 1. 2. 3. 4.]
[0 1 2 3 4]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [386]:
from io import StringIO
file = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
matrix = nmp.genfromtxt(file, delimiter=",", dtype=int)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [387]:

matrix = nmp.arange(4).reshape(2,2)
for index, value in nmp.ndenumerate(matrix):
    print(index, value)

print('--------')
for index in nmp.ndindex(matrix.shape):
        print(index, matrix[index])

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
--------
(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [388]:
X, Y = nmp.meshgrid(nmp.linspace(-1,1,3), nmp.linspace(-1,1,3))

D = nmp.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = nmp.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.60653066 0.36787944]
 [0.60653066 1.         0.60653066]
 [0.36787944 0.60653066 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [389]:
N = 4
p = 1
matrix = nmp.zeros((N,N))
nmp.put(matrix, nmp.random.choice(range(N*N), p, replace=False),1)
print(matrix)

[[0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [390]:
X = nmp.random.rand(2, 2)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)


[[ 0.13453863 -0.13453863]
 [ 0.03446841 -0.03446841]]


#### 59. How to sort an array by the nth column? (★★☆)

In [391]:
matrix = nmp.random.randint(0,10,(3,3))
print(matrix)
print(matrix[matrix[:,1].argsort()])

[[2 5 6]
 [1 7 7]
 [5 5 2]]
[[2 5 6]
 [5 5 2]
 [1 7 7]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [392]:
array = nmp.random.randint(0,1,(3,3))
print (array)
print((~array.any(axis=0)).any())

[[0 0 0]
 [0 0 0]
 [0 0 0]]
True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [393]:
array = nmp.random.uniform(0,1,10)
print(array)
given_value = 0.9
nearest_value = array.flat[nmp.abs(array - given_value).argmin()]
print(nearest_value)

[0.58428356 0.16092278 0.61475696 ... 0.31806619 0.32610482 0.88228726]
0.8822872648331274


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [394]:
array1 = nmp.arange(3).reshape(3,1)
print(array1)
array2 = nmp.arange(3).reshape(1,3)
print(array2)
it = nmp.nditer([array1,array2,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [395]:
class MyArray(nmp.ndarray):
    def __new__(cls, array, name="empty"):
        obj = nmp.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "empty")
arr = MyArray(nmp.arange(3),'123');
print(arr.name)


123


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [396]:
vector = nmp.ones(10)
I = nmp.random.randint(0,len(vector),20)
nmp.add.at(vector, I, 1)
print(vector)

[4. 3. 3. ... 2. 1. 4.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [397]:

vector = [1,2,3,4,5,6]
index_list = [5,4,3,2,1,0]
array = nmp.bincount(index_list,vector)
print(array)

[6. 5. 4. 3. 2. 1.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [398]:
width,height = 16,16
I = nmp.random.randint(0,2,(height,width,3)).astype(nmp.ubyte)
print(I)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
print(F)

n = len(nmp.unique(F))
print(n)

[[[0 0 1]
  [0 0 1]
  [0 1 1]
  ...
  [1 0 0]
  [1 0 1]
  [0 0 0]]

 [[0 1 0]
  [1 1 1]
  [1 0 0]
  ...
  [0 1 0]
  [1 1 0]
  [0 0 0]]

 [[1 0 0]
  [1 1 1]
  [1 1 1]
  ...
  [0 1 1]
  [0 1 0]
  [1 1 0]]

 ...

 [[1 1 0]
  [0 1 0]
  [0 0 1]
  ...
  [1 0 1]
  [1 1 1]
  [0 1 0]]

 [[0 1 1]
  [0 1 0]
  [1 1 0]
  ...
  [1 1 0]
  [0 0 1]
  [1 0 0]]

 [[1 1 1]
  [1 0 0]
  [0 1 0]
  ...
  [1 1 1]
  [1 1 1]
  [1 0 1]]]
[[    1     1   257 ... 65536 65537     0]
 [  256 65793 65536 ...   256 65792     0]
 [65536 65793 65793 ...   257   256 65792]
 ...
 [65792   256     1 ... 65537 65793   256]
 [  257   256 65792 ... 65792     1 65536]
 [65793 65536   256 ... 65793 65793 65537]]
8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [399]:
array4D = nmp.random.randint(0,4,(3,2,3,2))
sum = array4D.sum(axis=(-2,-1))
print(sum)

[[12  7]
 [ 2  9]
 [12  7]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [400]:
import pandas as pd;
vector1D = nmp.random.uniform(0,1,10);
print(vector1D)
S = nmp.random.randint(0,10,10)
print(S)
print(pd.Series(vector1D).groupby(S).mean())

[0.46798307 0.39009102 0.65941139 ... 0.8400445  0.41889796 0.03904621]
[9 0 3 ... 0 0 6]
0    0.549678
1    0.140268
2    0.553756
3    0.760467
6    0.039046
9    0.467983
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [401]:
A = nmp.random.uniform(0,1,(3,3))
B = nmp.random.uniform(0,1,(3,3))
nmp.diag(nmp.dot(A, B))

array([0.38414867, 1.03908051, 1.23601243])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [402]:
vector = nmp.array([1,2,3,4,5])
numberOfZeros = 3
vector_zeros = nmp.zeros(len(vector) + (len(vector)-1)*(numberOfZeros))
vector_zeros[::numberOfZeros+1] = vector
print(vector_zeros)

[1. 0. 0. ... 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [403]:
array1 = nmp.ones((5,5,3))
array2 = 2*nmp.ones((5,5))
print(array1 * array2[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [404]:
array = nmp.arange(9).reshape(3,3)
array[[0,1]] = array[[1,0]]
print(array)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [405]:
setOfTriplets = nmp.random.randint(0,100,(10,3))
F = nmp.roll(setOfTriplets.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = nmp.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
setOfUnique = nmp.unique(G)
print(setOfUnique)

[( 0, 27) ( 0, 57) ( 0, 81) ... (75, 90) (82, 93) (97, 99)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that nmp.bincount(A) == C? (★★★)

In [406]:
C = nmp.bincount([1,2,3,4,5])
A = nmp.repeat(nmp.arange(len(C)), C)
print(nmp.bincount(A) == C)

[ True  True  True  True  True  True]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [407]:
def func_75(a, n) :
    ret = nmp.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
array = nmp.arange(10)
print(func_75(array, n=3))

[1. 2. 3. ... 6. 7. 8.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [408]:
from numpy.lib import stride_tricks
def func_76(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
arrayZ = func_76(nmp.arange(10), 3)
print(arrayZ)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 ...
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inmplace? (★★★)

In [409]:
rray = nmp.random.randint(0,2,100)
print(array)
array=nmp.logical_not(array, out=array)
print(array)

array = nmp.random.uniform(-1.0,1.0,100)
print(array)
nmp.negative(array, out=array)
print(array)

[0 1 2 ... 7 8 9]
[1 0 0 ... 0 0 0]
[ 0.1977174   0.54663659  0.11808045 ... -0.83473802  0.24328217
 -0.76951538]
[-0.1977174  -0.54663659 -0.11808045 ...  0.83473802 -0.24328217
  0.76951538]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [410]:
def distanceFromP(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return nmp.sqrt((D**2).sum(axis=1))

P0 = nmp.random.uniform(-10,10,(3,2))
P1 = nmp.random.uniform(-10,10,(3,2))
p  = nmp.random.uniform(-10,10,( 1,2))

print(P0)
print(P1)
print(p)
print(distanceFromP(P0, P1, p))

[[ 8.29483685 -6.52476488]
 [ 4.58603596  8.31519885]
 [ 8.55807573  4.60959299]]
[[ 2.48441008 -2.14719923]
 [ 5.4605484   9.91721624]
 [ 8.35388959  2.5515635 ]]
[[-1.984821    5.27812683]]
[ 3.24127719  4.31230307 10.55739134]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [411]:
def distanceFromP(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return nmp.sqrt((D**2).sum(axis=1))

P0 = nmp.random.uniform(-10, 10, (3,2))
P1 = nmp.random.uniform(-10,10,(3,2))
p = nmp.random.uniform(-10, 10, (2,2))
print(nmp.array([distanceFromP(P0,P1,p_i) for p_i in p]))

[[ 2.0097763   0.65117198 12.17326965]
 [10.03845227  3.63919232 12.30496917]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [412]:
from numpy.lib import stride_tricks
array = nmp.arange(1,15,dtype=nmp.uint32)
R = stride_tricks.as_strided(array,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 ...
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [413]:
M = nmp.random.uniform(0,1,(5,5))
print(M)
U, S, V = nmp.linalg.svd(M)
rank = nmp.sum(S > 1e-10)
print(rank)

[[0.810704   0.07220663 0.96775974 0.5275966  0.79068256]
 [0.53275916 0.79769448 0.73865624 0.41060613 0.35002555]
 [0.92167618 0.58640799 0.81766253 0.15309    0.39682452]
 [0.74854258 0.51398092 0.21794864 0.72753428 0.95411392]
 [0.28972156 0.73880111 0.46066318 0.89784855 0.18630152]]
5


#### 83. How to find the most frequent value in an array?

In [414]:
array = nmp.random.randint(0,10,50)
print(nmp.bincount(array).argmax())

6


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [415]:
array = nmp.random.randint(0,5,(10,10))
n = 3
i = 1 + (array.shape[0]-3)
j = 1 + (array.shape[1]-3)
C = stride_tricks.as_strided(array, shape=(i, j, n, n), strides=array.strides + array.strides)
print(C)

[[[[3 4 0]
   [0 4 1]
   [0 2 4]]

  [[4 0 2]
   [4 1 0]
   [2 4 3]]

  [[0 2 2]
   [1 0 2]
   [4 3 4]]

  ...

  [[3 2 0]
   [3 0 0]
   [4 0 2]]

  [[2 0 3]
   [0 0 4]
   [0 2 4]]

  [[0 3 0]
   [0 4 4]
   [2 4 3]]]


 [[[0 4 1]
   [0 2 4]
   [0 2 4]]

  [[4 1 0]
   [2 4 3]
   [2 4 4]]

  [[1 0 2]
   [4 3 4]
   [4 4 4]]

  ...

  [[3 0 0]
   [4 0 2]
   [0 3 0]]

  [[0 0 4]
   [0 2 4]
   [3 0 1]]

  [[0 4 4]
   [2 4 3]
   [0 1 1]]]


 [[[0 2 4]
   [0 2 4]
   [1 4 4]]

  [[2 4 3]
   [2 4 4]
   [4 4 0]]

  [[4 3 4]
   [4 4 4]
   [4 0 3]]

  ...

  [[4 0 2]
   [0 3 0]
   [2 1 0]]

  [[0 2 4]
   [3 0 1]
   [1 0 0]]

  [[2 4 3]
   [0 1 1]
   [0 0 1]]]


 ...


 [[[1 3 1]
   [2 2 1]
   [4 3 4]]

  [[3 1 0]
   [2 1 2]
   [3 4 1]]

  [[1 0 3]
   [1 2 4]
   [4 1 0]]

  ...

  [[1 3 4]
   [4 1 0]
   [3 3 4]]

  [[3 4 3]
   [1 0 0]
   [3 4 3]]

  [[4 3 2]
   [0 0 0]
   [4 3 3]]]


 [[[2 2 1]
   [4 3 4]
   [4 0 2]]

  [[2 1 2]
   [3 4 1]
   [0 2 1]]

  [[1 2 4]
   [4 1 0]
   [2 1 3]]

  ...

  [[4

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [416]:
class Sym(nmp.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Sym, self).__setitem__((i,j), value)
        super(Sym, self).__setitem__((j,i), value)

def symetric(x):
    return nmp.asarray(x + x.T - nmp.diag(x.diagonal())).view(Sym)

S = symetric(nmp.random.randint(0,5,(6,6)))
S[2,3] = 42
print(S)

[[ 2  5  2  6  4  3]
 [ 5  4  4  4  0  6]
 [ 2  4  4 42  1  5]
 [ 6  4 42  1  0  8]
 [ 4  0  1  0  4  5]
 [ 3  6  5  8  5  4]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [417]:
p, n = 10, 20
M = nmp.ones((p,n,n))
V = nmp.ones((p,n,1))
S = nmp.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 ...
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [418]:
array = nmp.ones((16,16))
k = 4
sum = nmp.add.reduceat(nmp.add.reduceat(array, nmp.arange(0, array.shape[0], k), axis=0),
                                       nmp.arange(0, array.shape[1], k), axis=1)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [419]:
def iterate(array):
    
    N = (array[0:-2, 0:-2] + array[0:-2, 1:-1] + array[0:-2, 2:] +
         array[1:-1, 0:-2] + array[1:-1, 2:] +
         array[2:, 0:-2] + array[2:, 1:-1] + array[2:, 2:])

    
    birth = (N == 3) & (array[1:-1, 1:-1] == 0)
    survive = ((N == 2) | (N == 3)) & (array[1:-1, 1:-1] == 1)
    array[...] = 0
    array[1:-1, 1:-1][birth | survive] = 1
    return array


array = nmp.random.randint(0, 2, (50, 50))
for i in range(100): array = iterate(array)
print(array)


[[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [420]:

array = nmp.arange(1000)
nmp.random.shuffle(array)
n = 3

print(array[nmp.argsort(array)[-n:]])

[997 998 999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [421]:
def build_cartesian(arrays):
    arrays = [nmp.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = nmp.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (build_cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 ...
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [422]:
array = nmp.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
result = nmp.core.records.fromarrays(array.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
result

rec.array([(b'Hello', 2.5, 3), (b'World', 3.6, 2)],
          dtype=[('col1', 'S8'), ('col2', '<f8'), ('col3', '<i8')])

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [423]:
x = nmp.random.rand(123)

%timeit nmp.power(x,3)
%timeit x*x*x
%timeit nmp.einsum('i,i,i->i',x,x,x)

6.58 µs ± 2.05 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
877 ns ± 11 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
2.65 µs ± 337 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [424]:
array_A = nmp.random.randint(0,5,(8,3))
array_B = nmp.random.randint(0,5,(2,2))

array_C = (array_A[..., nmp.newaxis, nmp.newaxis] == array_B)
rows = nmp.where(array_C.any((3,1)).all(1))[0]
print(rows)


[0 2 3 4 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [425]:
array = nmp.random.randint(0,5,(10,3))
print(array)

result = array[array.max(axis=1) != array.min(axis=1),:]
print(result)

[[3 1 2]
 [3 4 3]
 [1 1 1]
 ...
 [2 3 1]
 [4 0 3]
 [4 3 4]]
[[3 1 2]
 [3 4 3]
 [3 1 2]
 ...
 [2 3 1]
 [4 0 3]
 [4 3 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [426]:
array=nmp.random.randint(0,2,(8,5))
print(array)
result = nmp.unique(array, axis=0)
print(result)

[[1 1 1 0 0]
 [0 1 0 1 0]
 [0 1 0 0 1]
 ...
 [0 0 1 1 0]
 [1 1 0 0 1]
 [1 0 0 0 1]]
[[0 0 1 1 0]
 [0 1 0 0 1]
 [0 1 0 1 0]
 ...
 [1 0 1 0 1]
 [1 1 0 0 1]
 [1 1 1 0 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [427]:

A = nmp.random.uniform(0,1,5)
B = nmp.random.uniform(0,1,5)

nmp.einsum('i->', A)
nmp.einsum('i,i->i', A, B)
nmp.einsum('i,i', A, B)
nmp.einsum('i,j->ij', A, B)

array([[0.16347446, 0.25544983, 0.12402589, 0.10719941, 0.23627217],
       [0.42822919, 0.6691631 , 0.32489178, 0.28081402, 0.61892631],
       [0.22346687, 0.34919568, 0.16954134, 0.14653982, 0.32298014],
       [0.31199161, 0.48752694, 0.23670387, 0.20459048, 0.45092632],
       [0.11157046, 0.17434317, 0.08464702, 0.07316304, 0.16125452]])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [428]:
F = nmp.arange(0, 10*nmp.pi, 0.1)
a = 1
x = a*F*nmp.cos(F)
y = a*F*nmp.sin(F)

diff_r = (nmp.diff(x)**2 + nmp.diff(y)**2)**.5
r = nmp.zeros_like(x)
r[1:] = nmp.cumsum(diff_r)
r_int = nmp.linspace(0, r.max(), 200)
x_int = nmp.interp(r_int, r, x)
y_int = nmp.interp(r_int, r, y)


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [429]:
array = nmp.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = nmp.logical_and.reduce(nmp.mod(array, 1) == 0, axis=-1)
M &= (array.sum(axis=-1) == n)
print(array[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [430]:
array = nmp.random.randn(100)
bootstrap_samples = 1000
idx = nmp.random.randint(0, array.size, (bootstrap_samples, array.size))
means = array[idx].mean(axis=1)
confint = nmp.percentile(means, [2.5, 97.5])
print(confint)

[-0.21698435  0.16500888]
